### ISSUE TITLE
Recommend a default cross platform virtual environment management tool

### ISSUE THREAD

**Issue by ncoghlan** [pypa/python-packaging-user-guide#118]
(Note: the issue scope broadened considerably over the course of the subsequent discussion. When reading the comments below, note that the early ones were responding to the original issue title and description, which are preserved below)

As you accumulate more virtual environments, it's useful to have a tool to help manage them (creating new ones, listing the ones that already exist, activating them, deactivating them, etc). virtualenvwrapper, pyenv, vex, pew - these kinds of things.

However, as with packaging tools themselves, new users are unlikely to have the knowledge they need to evaluate the trade-offs between the different tools that are available. In particular, the differences between creating a subshell (vex, pew), modifying the current shell session (virtualenvwrapper), and permanently modifying user configuration settings (pyenv) have different trade-offs in terms of the amount of assumed knowledge regarding the operation of the system shell,  as well as the chances of inadvertently impacting the operation of other Python applications on the system.

Considering just those four tools, and their complexity and potential for side effects, I'd assess them as follows:
- vex: aims to be shell independent, deliberately simple execution model & UI. Subshell model minimises chance of side-effects.
- pew: aims to be shell independent, aims to provide a full featured execution model & UI (comparable functionality to virtualenvwrapper).  Subshell model minimises chance of side-effects.
- virtualenvwrapper, pyenv: shell specific (written in shell code, not Python), which allows tighter integration with the shell, but also requires that the user have a greater understanding of shell programming (i.e. more than the bare essentials of "enter commands to run programs"). Altering the current shell session and/or user configuration files creates a relatively high chance of side effects on unrelated tools (potentially including system utilities and other Python applications that aren't configured to run in isolated mode).

In that context, I'd suggest that vex would be an appropriate recommendation as a minimal "getting started with environment management" solution. If a given user eventually decides they want something more configurable, or more closely integrated with their preferred shell environment, then they may want to explore pew, virtualenvwrapper or pyenv, and the packaging guide could point them in those directions (with some discussion of the associated trade-offs).

Outside the Python package management space, conda then takes the step up to being a full cross-platform platform, managing the Python runtime and arbitrary external dependencies, rather than just Python virtual environments. However, as an all-in-one solution that bundles environment management, dependency management and binary distribution, conda's operating in a different category from the more single-purpose tools being discussed here.

---

Original issue title: Mention "vex" somewhere (at least in the "Other projects" section)

Original issue description:

https://pypi.python.org/pypi/vex is a nice alternative to things like virtualenvwrapper that I discovered via the PyCon New Zealand lightning talks.

It works by creating _new_ subshells, rather than trying to alter the existing one. So deactivation is just a matter of exiting from the subshell.

This is really nice, because it's shell independent, and provides all the niceties of an integrated command line application, rather than a collection of shell functions.

**Comment by ncoghlan** [comment]
Eep, it's kinda scary to see how long ago I started this discussion :)

Anyway, a conversation today prompted me to revisit it in light of http://www.curiousefficiency.org/posts/2016/09/python-packaging-ecosystem.html, another few years of using `vex` regularly, and the creation of `pipenv` last year.

The key point is that while I still like `vex` for my own use, the fact that it *doesn't* follow the same traditional `<tool> <subcommand>` structure that `pip` uses is a problem from a learnability perspective.

The fact that `pew` supports operations like `pew inall pip install --upgrade pip setuptools wheel`, and `pew add` for sharing content between virtual environments are also major points in its favour.

We also know from `pipenv` that `pew` is viable as a building block for higher level more opinionated environment management tools.

So I think the way forward here would be to:

- draft a new entry in the [Guides](https://packaging.python.org/guides/) section covering "Managing virtual environments"
- recommend `pew` as a cross-platform virtual environment manager that will work with any Python runtime, regardless of how it was installed
- explicitly note that the optional runtime installation support doesn't currently work on Windows
- explicitly mention pyenv & conda as more opinionated environment managers that *only* work with the runtimes they provide themselves

**Comment by jonparrott** [comment]
@ncoghlan Sounds good to me - happy to review but I won't have time to author this anytime soon.

**Comment by pfmoore** [comment]
@ncoghlan Do we have confirmation that ```pew``` works reliably on Windows? From what I recall, I tried it some time ago (probably way back when you originally started this discussion) and found a number of bugs. When I reported them the ```pew``` developers were happy to accept patches but didn't have much in-house expertise on Windows. Having said that, I can't find those issues and the github project owner seems different, so it's possible I'm thinking of a different project. There seems to be specific support for powershell in ```pew```, which suggests they are covering Windows specifically.

I'm happy to recommend a tool, but IMO it's important that we're comfortable with its cross-platform support. I'll try to get a chance to check out ```pew``` again, but life's pretty hectic at the moment, so I can't promise.

**Comment by pfmoore** [comment]
Apologies - please ignore the above comment, I was getting confused between ```pew``` and ```pex```. I've got no reason to believe there's any issue with the Windows support of ```pew```.

**Comment by pfmoore** [comment]
Cool - sorry for the noise.

**Comment by ncoghlan** [comment]
Considering my answer to https://twitter.com/ncoghlan_dev/status/900547395095625728, another notable absence from the current tooling recommendations is the fact that we don't point anyone towards `pip-tools` or `pipenv` either, and frankly, if you're doing professional software development with Python (as opposed to ad hoc scripting), you should probably be using either conda or one of those two options.

I filed https://github.com/pypa/python-packaging-user-guide/issues/367 for that.

**Comment by ncoghlan** [comment]
I'm going to close this as:

1. #369 added a new tutorial that will recommend `pipenv` as the starting point for new users, rather than raw `pip`
2. `pipenv` not only integrates with `pew` for virtual environment management, but also integrates with `pyenv` for language runtime management

That still leaves Windows users without an automated option for managing the language runtimes themselves (short of switching to something like conda), but that's not going to be resolved here in PyPUG, since the problem is with the tooling not existing for that (as far as we're aware), rather than our failing to guide new users through a plethora of competing options.

So probably the best place to discuss that now would be on the `pipenv` repo, with actual Windows users and folks like @zooba considering whether it makes the most sense to try to add Windows support to `pyenv` itself, or to instead create a Windows-specific backend, and have `pipenv` use that. (I'm not going to file that issue though, since my Windows machine is pretty much solely for games these days)
