### ISSUE TITLE
Is Python3-only package installation forbidden on Linux machines?

### ISSUE THREAD

**Issue by einmalfel** [pypa/python-packaging-user-guide#135]
My project is written in Python 3 and is not compatible with version 2. Also, it doesn't have any C extensions.
I was going to package it for Linux (Windows and Mac compatibility might be added later).
Following python packaging user guide, I wrote a setup.py script and made other preparations, but when I went to a distribution part of a guide I found that there is two options:
- create a universal package that natively runs on both Python2 and Python3. Such package will be available on any system where PIP is installed.
- create platform package, which doesn't have to be compatible with both Python 2 and 3, but couldn't be installed from PIP on Linux.

So, my questions are:
1. Have I got it right? Is it indeed not allowed to upload Python3-only package for Linux?
2. If yes, what could I do with this? Supporting Python2 syntax is not an option.

**Comment by pfmoore** [comment]
If you just do ```setup.py bdist_wheel``` for a pure Python package, by default you'll get a package that runs only on Python 3 (or Python 2, if that's what you ran setup with).

There should probably be an extra section in the guide explaining this - it's likely it was left out for no better reason than that it's the default and someone forgot to mention it.

**Comment by pfmoore** [comment]
@einmalfel See #136 - does that clarify the situation sufficiently?

**Comment by einmalfel** [comment]
Please, explain the difference between the "wheel" described in a section you add and a "platform wheel" described further in the guide?
Both a created with `python setup.py bdist_wheel`.

**Comment by pfmoore** [comment]
@einmalfel Can you check #137 - @qwcode rewrote my attempt, does the new version adequately cover your concerns?

**Comment by einmalfel** [comment]
@pfmoore @qwcode
For me, it's now clear. Thanks

**Comment by pfmoore** [comment]
Thanks for pointing out the issue, and thanks @qwcode for refining my original attempt.
