### ISSUE TITLE
Mention pyscaffold in the Packaging Tutorial?

### ISSUE THREAD

**Issue by cpaulik** [pypa/python-packaging-user-guide#142]
I found [Pyscaffold](http://pyscaffold.readthedocs.org/) very useful for creating my packages, especially since it also integrates with Shinx and pytest. Could this be mentioned in the Guide or is there a reason why this is not a good idea?

**Comment by ncoghlan** [comment]
I'm going to belatedly declare this one as out of scope, as the packaging guide is maintained by the Python *Packaging* Authority, and we don't actually have a strong collective opinion on project templating tools. Keeping the scope of the guide under control is already a tough problem, and letting it expand beyond strictly packaging related topics would make that challenge even worse, so a good rule of thumb is that if a given area would be off-topic for distutils-sig, it's also off-topic for the user guide.

An additional problem with this and similar tools is that there are a number of them, and different folks will have different tastes in the templates that appeal to them. Without counting the project wizards that come with IDEs, the other two main Python project templating engines I'm personally aware of are cookiecutter and DevAssistant.
