### ISSUE TITLE
Update description of conda package manager

### ISSUE THREAD

**Issue by kerrywatson1** [pypa/python-packaging-user-guide#148]
The description of conda from 2013 is outdated. I would like to replace it with something like the following. I'm new to github editing so wanted to post it before attempting to edit, please be kind in letting me know if I've broken any protocols, thanks.

"The conda cross-platform package manager

Anaconda is a Python distribution published by Continuum Analytics. It is a stable collection of  Open Source packages for big data and scientific use.  About 100 are installed with Anaconda 2.2, and a total of 279 can be installed and updated from the Anaconda repository. 

Conda is an open source (BSD licensed) package management system and environment management system that allows users to install multiple versions of binary software packages and their dependencies, and easily switch between them. It is a cross-platform tool working on Windows, OSX, and Linux. Conda can be used to package up and distribute all kinds of packages, it is not limited to just Python packages.   It has full support for native virtual environments. Conda makes environments first-class citizens, making it easy to create independent environments even for C libraries. It is written in Python, but is Python-agnostic. Conda installs Python directly in contrast to pip which does not.  Conda is available in Anaconda and Miniconda (an easy-to-install download with just Python and Conda). "

**Comment by qwcode** [comment]
no protocols broken.... you can proceed to a PR.

**Comment by kerrywatson1** [comment]
Thanks @qwcode I believe this is complete... please check and let me know if I can merge it.

**Comment by kerrywatson1** [comment]
> I''m happy to merge this, but can you elaborate more on "Conda installs Python directly in contrast to pip which does not"

@qwcode Okay I believe I have addressed your concerns, please let me know if not. Thanks for your help!

**Comment by qwcode** [comment]
ok, merged.  thanks.
