### ISSUE TITLE
appveyor.yml missing Python 3.5

### ISSUE THREAD

**Issue by hickford** [pypa/python-packaging-user-guide#174]
The [`appveyor.yml` example](https://github.com/pypa/python-packaging-user-guide/blob/master/source/code/appveyor.yml) at is missing Python 3.5

https://packaging.python.org/en/latest/appveyor/

**Comment by hickford** [comment]
I had a go https://github.com/pypa/python-packaging-user-guide/pull/172

**Comment by nedbat** [comment]
Shouldn't it work to just take the two files from the appveyor demo repo?

**Comment by hickford** [comment]
You mean [python-appveyor-demo](https://github.com/ogrisel/python-appveyor-demo/)? Maybe, let me try it. Their `run_with_env.cmd` looks a bit more complex than our `run_with_compiler.cmd`

2. https://github.com/ogrisel/python-appveyor-demo/tree/master/appveyor
1. https://github.com/pypa/python-packaging-user-guide/tree/master/source/code

**Comment by hickford** [comment]
Assuming it works, we should probably make the two repos consistent.

**Comment by hickford** [comment]
Fixed by https://github.com/pypa/python-packaging-user-guide/commit/94fcc0f1d58c628f1bb4213b2033f37ba0db0372#diff-d477b16812c9d7eb4f92bd98c24212d5R13
