### ISSUE TITLE
Distutils wiki should note it's out of date and refer users to the PyPA

### ISSUE THREAD

**Issue by Russell-Jones** [pypa/python-packaging-user-guide#187]
https://wiki.python.org/moin/Distutils

This comes up on some Google searches. From [Nobody Expects the Python Packaging Authority](https://www.youtube.com/watch?v=8Xrdt3-YVz4) I understand that part of the aim of the PyPA is to reduce confusion about Python packaging. I think this would help with that.

**Comment by pfmoore** [comment]
As the above is a wiki, this can be changed by any interested party. Would you be interested in making the necessary edits?

**Comment by Russell-Jones** [comment]
Ah, thanks. I kind of assumed that it would be editable by known developers only.

... and this seems to be so. I either don't have edit rights (I just created the user "Russell Jones" on the wiki) or the pages have been set to be "Immutable" in some way as the LHS has the text "Immutable Page".

**Comment by ncoghlan** [comment]
On 22 November 2015 at 00:38, Russell-Jones <notifications@github.com> wrote:
>
> Ah, thanks. I kind of assumed that it would be editable by known developers only.

I've at least adjusted the top of the page to direct readers to the
packaging user guide and the PyPA home page:
https://wiki.python.org/moin/Distutils

However, the rest of the content should likely still be reviewed to
see what's worth keeping, and what can safely be discarded from the
current wiki.

> ... and this seems to be so. I either don't have edit rights (I just created the user "Russell Jones" on the wiki) or the pages have been set to be "Immutable" in some way as the LHS has the text "Immutable Page".

MoinMoin's automated defences against spam account sign-ups are
unfortunately limited, so there's an email based step in requesting
edit permissions: https://wiki.python.org/moin/FrontPage#use

Regards,
Nick.

-- 
Nick Coghlan   |   ncoghlan@gmail.com   |   Brisbane, Australia

**Comment by Russell-Jones** [comment]
Thanks for fixing up the page (and Python packaging in general :) ) There are 37 pages on the wiki and some have not much stuff on. I'll have a look through this evening or tomorrow.
