### ISSUE TITLE
Add build instructions to the README

### ISSUE THREAD

**Issue by ddbeck** [pypa/python-packaging-user-guide#207]
Currently, building and viewing the guide locally is undocumented. The README file would probably be a good place to add this information. **This issue would be an excellent task for a first-time contributor** with basic familiarity with the command line and installing things with pip.

Here are the rough steps to complete this task:
1. Fork this repository.
2. In your fork, edit `README.rst` (the file uses reStructuredText markup which is similar to Markdown; see [this reStructuredText reference](http://docutils.sourceforge.net/docs/user/rst/quickref.html) for help).
   
   Add a new section heading ("How to build this guide", perhaps) and step-by-step instructions. Here's how you build the docs:
   - Sphinx is required to build the docs. You can install it with `pip install Sphinx`.
   - The build command is `make html` (or on Windows `make.bat html`).
   
   Once you've built the guide, you can open `build/html/index.html` in a web browser to see the guide. You should try following your instructions to make sure they work before opening a pull request.
3. Commit your changes and push to your fork.
4. Open a pull request and mention this issue.

That's it! Please comment if you need any help. Thanks!

(And if you like this, check out issue #194 where there's lots more to help out with!)

**Comment by souravsingh** [comment]
I will be working on this.

**Comment by souravsingh** [comment]
I have added the instructions in my fork of the project.They can be accessed here at https://github.com/souravsingh/python-packaging-user-guide/commit/e8177c917d04b70fab3945a485036f51cd66

**Comment by ddbeck** [comment]
@souravsingh I was hoping that this issue would present an opportunity for someone who has not yet contributed to do so, since some volunteers indicated that they were new to GitHub and Python (plus, it's not germane to your existing pull request, complicating the review process). Would you be willing to hold off submitting this for a while, to give a first timer a chance to attempt it?

**Comment by souravsingh** [comment]
@ddbeck I made a mistake of editing the README within the develop branch and I am really sorry about it. As for the issue, I didn't know that the issue was for Python newbies.So I am willing to hold off on it.

**Comment by souravsingh** [comment]
@ddbeck Would it be good if we can add a tag to some of the issues saying something like "low-hanging-fruit" or "newbie-friendly" to bring newbies into making their first PR?

**Comment by ddbeck** [comment]
@souravsingh That's an excellent idea! I ought to tag all the new tutorials stuff too. I'll do that this evening.

**Comment by Menuka5** [comment]
Hello @ddbeck I'm New new to GitHub and Python. Is this opportunity still available? I would love to learn and contribute.

**Comment by jonparrott** [comment]
@Menuka5 yep! This is still available. However, @ddbeck's instructions only need to be tweaked slighty:

1. [Nox](https://nox.readthedocs.io) is required to build the guide locally. You can install Nox using `pip install nox-automation`.
2. To build the docs, run `nox -s build`. You can build the docs and start a local web server to preview the docs by running `nox -s preview`.

**Comment by ddbeck** [comment]
Hi @Menuka5, thanks for taking an interest in this issue! @jonparrott is right about those changes. If you need any help with making the pull request, feel free to ask questions here, and I'll do what I can.

**Comment by Menuka5** [comment]
Thank you @ddbeck and @jonparrott I forked the repository and currently learning ReStructuredText for documentation. I may need a help since I haven't done any pull request before :)

**Comment by Menuka5** [comment]
Hi @ddbeck and @jonparrott I completed the task https://github.com/Menuka5/python-packaging-user-guide Your feedback is highly appreciated

**Comment by jonparrott** [comment]
@Menuka5, could you send a pull request? See [here](https://help.github.com/articles/github-flow/) for some instructions, but feel free to ask us for help.

**Comment by Menuka5** [comment]
@jonparrott I think I made the pull request

**Comment by Menuka5** [comment]
@jonparrott and @ddbeck Thank you for helping me :)
