### ISSUE TITLE
Guidlines for making a PyPI-friendly readme

### ISSUE THREAD

**Issue by ddbeck** [pypa/python-packaging-user-guide#210]
A [warehouse issue](https://github.com/pypa/warehouse/issues/876) brought up the idea of documenting how to format code in READMEs for PyPI. Rather than covering code formatting alone, I thought it might be useful to have a section that covers setting the contents of a project's PyPI home page:
- explaining where the content of a project's page on PyPI comes from (i.e., `long_description`)
- setting the contents of `long_description` to the content of a project's README file (like the [pypa sample project does](https://github.com/pypa/sampleproject/blob/master/setup.py#L16))
- using ReST to format the document and specifically calling attention to the PyPI-specific case of pygments lexers

Before I started writing, I thought I would open this issue for feedback or additional ideas.

**Comment by dstufft** [comment]
Note: you can test a long_description using the exact same code that PyPI (and Warehouse) uses (modulo version numbers) using:

```console
$ pip install readme
$ python setup.py check -r -s
```

**Comment by brainwane** [comment]
@njsmith suggested it might also be good to link to https://pypi.python.org/pypi/pyroma .

**Comment by brainwane** [comment]
I now see that https://packaging.python.org/tutorials/distributing-packages/?highlight=https#uploading-your-project-to-pypi does mention [readme_renderer](https://github.com/pypa/readme_renderer/).

I do think a bit more explanation, mapping bits of the README to bits of a PyPI project detail page, would be useful.

**Comment by brainwane** [comment]
The packaging and distribution tutorial currently says:

> All projects should contain a readme file that covers the goal of the project. The most common format is reStructuredText with an “rst” extension, although this is not a requirement.

I think that right now we should just say it is a requirement, to simplify the experience for users, till the multiple steps laid out in https://github.com/pypa/warehouse/issues/869#issuecomment-340928703 are completed. This would also reduce conflict with [the sample project README](https://github.com/pypa/sampleproject/blob/master/README.rst) which says that it should be written in reStructuredText.

This would reduce confusion. I was advising a person today who was trying out the new PyPI who asked,

> 2. The docs say that rst isn't the only format for readmes, but don't say what other formats are accepted. Can it handle markdown? 

Until we can confidently list what other formats will render well, let's just advise people to use `.rst`.

**Comment by di** [comment]
I think the docs are implying that plaintext is also an option, if users don't want to use reStructuredText.

**Comment by ncoghlan** [comment]
Right, the two currently fully supported formats are plain text (`*.txt`) and reStructuredText (`*.rst`). It works out that way because PyPI attempts to render with https://pypi.python.org/pypi/readme_renderer and if that fails, it treats the description as plain text.

`*.md` doesn't render as ReST, so it ends up being handled as plain text.

**Comment by ncoghlan** [comment]
Also worth noting: PEP 566 has been accepted, so I'd expect Markdown to be supported properly over the next couple of months (`pypi.python.org` will still render them as plain text, but `pypi.org` will render them properly)

**Comment by nnadeau** [comment]
@ncoghlan do you have a branch/PR/issue we can follow for Markdown support?

**Comment by di** [comment]
@nnadeau You can follow https://github.com/pypa/warehouse/issues/869, which I will close once it's possible to publish a package with a Markdown description with some subset of packaging tools.

**Comment by brainwane** [comment]
@di posted it in pypa/warehouse#869 but it's worth pointing to here as well: [with releases or pre-releases available of all the tools in the packaging and distro toolchain, you can now build and upload an sdist to Warehouse with a Markdown `README`](https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi)!

Followups:
* pypa/wheel#231
* pypa/warehouse#869

**Comment by brainwane** [comment]
@ddbeck If you are interested in writing "make a PyPI-friendly `README`" as a Guide, I for one would welcome it.

**Comment by ddbeck** [comment]
@brainwane good timing on reminding me of this! I actually have some time for this either tomorrow or Monday. Feel free to nudge me about it if there's no progress by Tuesday. :-)

**Comment by ddbeck** [comment]
OK, I've opened a PR to add a guide. I ultimately did not cover testing README rendering because the `setup.py` check doesn't seem to check Markdown yet. But maybe it's something we can cover later.

**Comment by brainwane** [comment]
Per https://github.com/pypa/warehouse/issues/3438#issuecomment-376654131 I would love for https://packaging.python.org/guides/making-a-pypi-friendly-readme/ to mention the minimum versions of these tools folks will need:

* `pkginfo>=1.4.2`
* `twine>=1.11.0`
* `setuptools>=38.6.0`
* `wheel>=0.31.0`

**Comment by di** [comment]
I've already made a separate issue for that: https://github.com/pypa/python-packaging-user-guide/issues/481

Also should not that the `pkginfo` requirement is satisfied by upgrading `twine`, so we probably don't need to explicitly mention it.

**Comment by ddbeck** [comment]
OK, the README guide merged and the other issue is open so I'm going to close this. Thanks, everyone!
