### ISSUE TITLE
Docs: "Upload your distributions"

### ISSUE THREAD

**Issue by guettli** [pypa/python-packaging-user-guide#231]
Most users don't read from top to bottom.

If you look at this part, then there is one information missing:

{{{
Upload your distributions

Finally, you can upload your distributions to PyPI.

There are two options:

    Use twine

    twine upload dist/*

}}}
From: http://python-packaging-user-guide.readthedocs.org/en/latest/distributing/#upload-your-distributions

I am missing: Where do the files in "dist/*" come from?

I search for "dist/" on the page (ctrl-f). The matches I found did not explain where these files in this directory come from.

I don't want much, just a sentence like this:

> You can now upload the files created in Link-To-Matching-Step-In-Docs with ...

**Comment by annaraven** [comment]
So you want a phrase like "You can now upload the files created by packaging up your project as described in #packaging your project"? Given it's the very previous section, easily found by scrolling up one window(even on my tiny screen), I'm not convinced this would be helpful. 

However, I could see adding something like: "The first time you run the sdist or bdist command will create a new directory in your project, called dist/, and put the new .whl or .tar.gz there." might be helpful. 

Think that would be useful? You could easily find it then with ctrl-f even if you missed it in scrolling.

**Comment by guettli** [comment]
@annaraven Yes, your sentence would make more sense, then mine:

> The first time you run the sdist or bdist command will create a new directory in your project, called dist/, and put the new .whl or .tar.gz there.

BTW, I don't like "or" in docs much. Is there a common term which matches for both file extensions?

**Comment by annaraven** [comment]
Okay, how about "The first time you run the command to package up your project, a new directory will be created called dist/, and the new distribution file will be put there."

**Comment by ncoghlan** [comment]
Closing this one based on @annaraven's PR.

**Comment by guettli** [comment]
Thank you for fixing this small issue.

**Comment by ncoghlan** [comment]
I mentioned the wrong issue in the commit message for https://github.com/pypa/python-packaging-user-guide/commit/094aad139bb2f3dcec4cee4d925970eacb1b62e5 - the correct reference is to #238
