### ISSUE TITLE
Cover using Warehouse for uploads?

### ISSUE THREAD

**Issue by ncoghlan** [pypa/python-packaging-user-guide#241]
@dstufft recently posted some notes to distutils-sig on using the parallel Warehouse deployment for uploads in order to bypass the stability problems on the legacy PyPI service: https://mail.python.org/pipermail/distutils-sig/2016-June/029083.html

I'm wondering if it may make sense to include explicitly configuring that as interim guidance in the packaging guide until we've fully cut over to pypi.io as the default service endpoint.

@qwcode @ddbeck Thoughts?

**Comment by dstufft** [comment]
Not sure if it's worth it. I hope to switch the default in twine in < 1 month, and if that goes well, the default in 3.5.**3** and 3.6, etc.

**Comment by ncoghlan** [comment]
Sounds like a plan. I'll leave this open until then though - the fact twine uses Warehouse for uploads can be mentioned in a footnote as another good reason for using twine.

**Comment by dstufft** [comment]
The twine PR is https://github.com/pypa/twine/pull/177.

**Comment by ncoghlan** [comment]
(To be clear: i don't think this is an urgent priority, I just noticed it as a documentation gap and this seemed like a good place to make note of it)

Does twine have its own docs? Your discussion with @annaraven on the twine PR made me realise we likely need to document this *somewhere* for the sake of folks trying to dig deeper into the architectural relationships between the PyPI service and the client tools.

Another option might be to add an "Architectural Overview" section to https://www.pypa.io/en/latest/ that covers the various service URLs for both legacy PyPI and the Warehouse deployment, including the test instances.

**Comment by dstufft** [comment]
Twine's only real documentation is it's README file.

**Comment by annaraven** [comment]
I just created a PR to change the packaging user guide to reflect the change.

**Comment by ncoghlan** [comment]
Closing based on @annaraven's tweak to the example configuration.
