### ISSUE TITLE
Naming!

### ISSUE THREAD

**Issue by dstufft** [pypa/python-packaging-user-guide#246]
I'm working on getting a new EV certificate for the PSF, and currently ``packaging.python.org`` is one of the things that we have on that EV certificate. However, in the process of that it occurred to me that since PyPI is getting a new URL with Warehouse (``pypi.io``) that maybe it would make sense to hang this off of that too, instead of where it's at now. Of course, if we did that, we'd redirect ``packaging.python.org`` to the new domain name so that no old links and such would break.

Off the top of my head, I'm thinking something like ``guides.pypi.io`` (inspired by ``http://guides.rubygems.org/``) might be a good name? It's both shorter than ``packaging.python.org`` and I think it's a bit more memorable (particularly since we also have the old ``packages.python.org``) and more obvious what it holds versus the current name.

Thoughts?

**Comment by ncoghlan** [comment]
I'd suggest docs.pypi.io as the specific subdomain (to align with docs.python.org), but +1 for the general idea of moving the canonical URL to a subdomain of the new top level one.

**Comment by dstufft** [comment]
@ncoghlan I thought about docs.pypi.io, but I wasn't sure how I liked that-- particularly since, unlike docs.python.org, this *isn't* the canonical documentation for any one particular thing but is more along the lines of a recipe book for how to combine the various things to do something reasonable. Also it'll be harder for browser autocomplete to make a mistake between ``guides.pypi.io`` and ``docs.python.org`` then it will be for ``docs.pypi.io`` and ``docs.python.org``.

Maybe that still makes sense for it to be ``docs.pypi.io`` I dunno.

**Comment by ncoghlan** [comment]
I think those are both valid points (especially the one about it being primarily usage guides for tools with their own official documentation maintained elsewhere), so I'd be happy with guides.pypi.io

**Comment by ddbeck** [comment]
I'm happy with `guides.pypi.io`, but it might also make sense to have `docs.pypi.io` point to Warehouse's documentation (i.e., a redirect to https://warehouse.pypa.io/), or to keep `docs.pypi.io` in reserve for a portal (for lack of a better word, believe me I'm cringing about that one) to direct different audiences to the docs that they're looking for.

**Comment by Ivoz** [comment]
I actually like `packaging.python.org` for the reason that it is obvious to any newcomer that this is an official, should-be-correct source of information. That is to contrast with, some personal wordpress blog from 2013 that they read beforehand. If I provide an answer to someone and reference with a url from `packaging.python.org` they'll likely immediately know it's correct information.

`guides.pypi.io` to me, gets across this suggestion less effectively since `pypi.io` is not `python.org`.

**Comment by pfmoore** [comment]
I agree with @Ivoz, ```packaging.python.org``` is both memorable and discoverable IMO.

Also, I just realised, we have both ```pypa.io``` (where the pip docs are hosted, at least currently) and now ```pypi.io``` is being proposed. That's a recipe for endless confusion (getting confused is how I spotted the issue in the first place!), and I'm afraid I'm a strong -1 on hosting the docs under the ```pypi.io``` domain for that reason. Even if we ```pypi.io``` was a typo, and @dstufft meant ```pypa.io```, it's clear from this whole discussion that there's the possibility of confusion...

**Comment by dstufft** [comment]
I mean, people are going to have to deal with the ``pypi.io`` domain either way since that's where PyPI is going to be living at. We're moving it from ``pypi.python.org`` to there when warehouse launches. In my opinion keeping it alongside the primary domain users will be interacting with for packaging related tasks seems to be a net win. Confusion with ``pypa.io`` is a possibility, perhaps the way to resolve that is by combining the two domains. Currently we have under ``pypa.io``:

* The top level domain which holds some generic information about PyPA as a whole as well as some high level road maps and such.
* ``bootstrap.pypa.io`` which holds the bootstrap scripts for people.
* ``*.pypa.io`` which holds the documentation for individual projects.

We could switch this around so that we instead (while maintaining redirects so as not to break anything) have:

* ``docs.pypi.io`` which at the top level holds the generic PyPA information as well as linking to all of the docs for the individual PyPA projects.
* ``docs.pypi.io/projects/*/`` which holds the documentation for each of the PyPA projects using the RTD sub projects feature (example: http://celery.readthedocs.io/projects/kombu/en/latest/).
* Alternatively, we could use ``*.docs.pypi.io`` if we want to maintain the shorter links with the project in the domain name.
* ``bootstrap.pypi.io`` which does the same thing as what ``bootstrap.pypa.io`` does not.

Personally I feel like keeping it tied with ``pypi.io`` which will become the place that people go to for packages themselves make sense, and I don't think that ``packaging.python.org`` is discoverable since folks aren't going to be randomly typing URLs into their browsers anyways. They'll either remember it or click on a link somewhere to it.

**Comment by dstufft** [comment]
Ok, so I need to get moving on the EV certificate and I'd like to add either ``packaging.python.org`` OR ``guides.pypi.io``, but not both to this certificate (we have a limited number of slots). What do folks think about my idea above, does that fix the problems that @pfmoore and @Ivoz saw with using ``guides.pypi.io``?

I should note, that in either case this is going to have an EV certificate that says in fairly obvious wording ``Python Software Foundation [US]``, so it's not just relying on the domain name itself.

**Comment by pfmoore** [comment]
I'm not 100% sure I understand your proposal. Are you suggesting having ```pypi.io``` as the main domain, with ```pypa.io``` being effectively retired (with links retained for legacy, but the canonical locations being ```pypi.io```)? If so then that sounds OK - my major objection is having *both* ```pypi.io``` and ```pypa.io``` in active use, that seems far too likely to confuse users.

Maybe "discoverable" wasn't the right word. "Memorable" is better. I find it *really* easy to remember ```packaging.python.org``` as it's where I look for packaging information for python. I suppose I could get used to ```guides.pypi.io``` as an alternative, but it doesn't seem as obvious to me.

(On a personal, and tangential, note, I find the ```.io``` domain a lot less memorable than the ```.org``` domain - years of having ```.com```, ```.org``` and ```.co.uk``` as basically the "big three" domains for anything I use, makes other TLDs more of an effort to remember. Maybe that's just me, though).

**Comment by dstufft** [comment]
@pfmoore Yes. We're going to have ``pypi.io`` regardless because that's where PyPI is moving to so if folks find having both confusing then we should centralize around that one (or come up with a new one for ``pypa.io``, but I don't think that's needed).

Calling ``packaging.python.org`` more memorable than ``guides.pypi.io`` makes sense. I wonder how much of that is just because you already have ``python.org`` in your head versus how much is inherent (for my own case, I find ``packaging.python.org`` less memorable because my brain keeps confusing it with ``packages.python.org``).

We tried to get ``pypi.org`` but the guy who owns it wanted several thousand dollars for it. I did own cheeseshop.org that I suggested as a renaming of PyPI to Cheeseshop but folks didn't like that idea, so we ended up needing to use a different tld, and ``.io`` seemed like the best option.

**Comment by dstufft** [comment]
Oh, and the other question is, if we standardize around ``pypi.io``, should docs be something like:

* ``docs.pypi.io/projects/pip/en/latest/``
* ``pip.docs.pypi.io/en/latest/``
* ``docs.pypi.io/pip/en/latest/``

**Comment by dstufft** [comment]
Hit enter too soon :(

It's important to note, that of those three, the first two I know for a fact are achievable easily, and the third I *think* is achievable but may not actually be.

**Comment by ncoghlan** [comment]
For me, memorability is related to pronouncability - "python.org" is four
syllables (pie-thon-dot-awg), while an unambiguous pypi.io is six
(pie-pee-eye-dot-eye-oh). So going from pypi.python.org to pypi.io is a win
(10 syllables down to six), while going from packaging.python.org to
guides.pypi.io is equivalent on syllable count, but adds that horrible
"eye-eee-eye" transition that previously wasn't needed when giving the docs
URL.

I'm also not sure the "people will follow a link" assertion is true - while
I'd expect links to be the *main* referrer, I know I tell people "start at
packaging.python.org and follow the links from there", and I personally
often rely Firefox filling it in from my browser history after I start
typing "pack...". I just don't know the likely proportion of the two groups.

That said, I think there's an even more important reason to keep the
python.org naming scheme: many of these docs apply even if you're not using
PyPI at all (e.g. you may be solely interacting with a private devpi
instance). That means they really are Python ecosystem docs, not PyPI docs.

**Comment by pfmoore** [comment]
I still prefer ```packaging.python.org``` for the reasons Nick covered (plus the fact that I pronounce ```pypi``` as "pie-pie" and that clashes with ```pypy```, which I think is a common confusion). But I'm not going to make a huge issue over it - I've made my point on that now.

> Oh, and the other question is, if we standardize around pypi.io, should docs be something like:

> * ```docs.pypi.io/projects/pip/en/latest/```
> * ```pip.docs.pypi.io/en/latest/```
> * ```docs.pypi.io/pip/en/latest/```

As for the 3 options, I assume the ```/en/latest/``` part will be handled by a redirect, so it's effectively

1. ```docs.pypi.io/projects/pip```
2. ```pip.docs.pypi.io```
3. ```docs.pypi.io/pip```

My preference would be 2 or 3 (no real opinion) with 1 definitely behind. Also, is there any reason to not use ```pip.pypi.io/docs``` (with other pip-related stuff also under ```pip.pypi.io```), which I think would be preferable to any of the above 3?

**Comment by dstufft** [comment]
Okay, then we'll keep ``packaging.python.org``.

> Also, is there any reason to not use pip.pypi.io/docs (with other pip-related stuff also under pip.pypi.io), which I think would be preferable to any of the above 3?

Um, mostly just namespace collisions since we'd have other stuff at that same level so we'd have to be careful not to have names clash.
