### ISSUE TITLE
404 for Project Summaries page

### ISSUE THREAD

**Issue by ncoghlan** [pypa/python-packaging-user-guide#253]
I'm getting a 404 clicking on the Project Summaries link on the main index, which goes to https://packaging.python.org/projects/

Specifying https://packaging.python.org/projects/index.html explicitly also fails.

However, if I do "make dirhtml" locally, the page renders fine.

It also fails if using the default RTFD provided domain: http://python-packaging-user-guide.readthedocs.io/projects/

**Comment by ncoghlan** [comment]
This could be due to a collision with the paths used for the subprojects feature: http://read-the-docs.readthedocs.io/en/latest/faq.html#how-do-i-host-multiple-projects-on-one-cname

**Comment by ncoghlan** [comment]
Escalated to RTFD at https://github.com/rtfd/readthedocs.org/issues/2292

Alternatively, since this page is mostly used for internal references within the docs (as far as we know, anyway), we could just rename it to something like "key_projects.rst" and avoid the collision that way.

**Comment by ncoghlan** [comment]
@dstufft, @qwcode - unless I hear any objections, I'll go ahead and make that change tomorrow my time (so within 12-18 hours or so)

**Comment by ncoghlan** [comment]
I merged the rename in #254 so the front page link is working again now, and so should any cross-references from other parts of the docs.

**Comment by Ivoz** [comment]
I have also just got 404's on https://packaging.python.org/additional/ and https://packaging.python.org/distributing/

They were 404ing for a couple of minutes before finally rendering completely normally, for an inexplicable reason. I found this after being told by someone else it was happening for them.

https://i.imgur.com/KN0LTZx.png <- image of a tab that hadn't been refreshed yet if anyone is struggling to believe me.

**Comment by dstufft** [comment]
It looks like something is up with RTD:

```
$ curl -I https://readthedocs.io/ -H 'Host: packaging.python.org'
HTTP/1.1 404 OK
Server: nginx/1.10.0 (Ubuntu)
Vary: Accept-Encoding
Vary: Cookie, Accept-Language
Content-Type: text/html; charset=utf-8
Date: Sun, 18 Sep 2016 15:52:21 GMT
Transfer-Encoding: chunked
Content-Language: en
Connection: Keep-Alive
```


However, it's toggling between 200, 403, and 404. We have Fastly in front of RTD so it'll get cached too.
