### ISSUE TITLE
Register using twine fails if following the guide

### ISSUE THREAD

**Issue by lmazuel** [pypa/python-packaging-user-guide#263]
Hi,

I tried to register my package using Twine as described here:
https://packaging.python.org/distributing/#register-your-project

I got a message that the API is no longer supported:
on test server:

``` bash
> twine register -r test .\azure-mgmt-batch-1.0.0.zip
Registering package to https://test.pypi.org/legacy/
Registering azure-mgmt-batch-1.0.0.zip
HTTPError: 410 Client Error: This API is no longer supported, instead simply upload the file. for url: https://test.pypi.org/legacy/
```

on prod server:

``` bash
> twine register .\azure_mgmt_batch-1.0.0-py2.py3-none-any.whl
Registering package to https://upload.pypi.org/legacy/
Registering azure_mgmt_batch-1.0.0-py2.py3-none-any.whl
HTTPError: 410 Client Error: This API is no longer supported, instead simply upload the file. for url: https://upload.pypi.org/legacy/
```

If the API is no longer supported, does this mean that `twine register` is not working anymore and that the doc needs to be changed?

Version:

``` bash
> twine --version
twine version 1.8.1 (pkginfo: 1.3.2, requests: 2.11.0, setuptools: 25.1.6,
requests-toolbelt: 0.7.0, clint: 0.5.1)
```

@brettcannon

**Comment by jacebrowning** [comment]
Related bug in `twine` itself: https://github.com/pypa/twine/issues/200

**Comment by dholth** [comment]
Right now uploading the file does what register used to do,  plus the file of course.

**Comment by johnyf** [comment]
Attempting `python setup.py register` with PyPI raises the API error mentioned in the OP. However, `python setup.py upload` does not properly register the package's metadata on PyPI (I noticed all but one keyword missing, whereas in the past all were present).

Using `twine register` corrected the issue, by successfully registering the keywords of a package that had already been uploaded to PyPI using `python setup.py upload`. Not sure whether using `twine upload` to start with would have avoided the issue (will found out the next time I release a new version).

Please let me know whether this sounds reasonable, or I should report a bug (to legacy PyPI maybe, or `warehouse`) about the missing keywords.
