### ISSUE TITLE
The used license should be distributed or not with the package?

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [pypa/python-packaging-user-guide#275]
Legal question:
Example of task: Creating Python pypa project with MIT license.
In your user guide the MIT license is only setup in setup.py is this good enough?
Or (MIT) LICENSE(.txt) file should be included in the package as well?
http://choosealicense.com/licenses/mit/

**Comment by jonparrott** [comment]
Most downstream packagers (e.g., linux distributions) really want to have a LICENSE file in the package. In general, it's always best avoid ambiguity with your package's license:

1. Include a license header in every human-created source file.
2. Include LICENSE in your SCM, source distributions (.zip, .tar.gz, python setup.py sdist), and binary distributions (.whl, python setup.py bdist_wheel).
3. Include the license metadata in `setup.py`.
