### ISSUE TITLE
Additional topic for plugin management?

### ISSUE THREAD

**Issue by ncoghlan** [pypa/python-packaging-user-guide#291]
Reviewing @jonparrott's PR for an Additional Topic on Namespace Packages (https://github.com/pypa/python-packaging-user-guide/pull/290) that reviewed the available options made me wonder whether or not it might be worth doing a similar comparison between entry points based plugins (http://setuptools.readthedocs.io/en/latest/setuptools.html#dynamic-discovery-of-services-and-plugins), and namespace based plugins using https://docs.python.org/3/library/pkgutil.html#pkgutil.iter_modules (or higher level helpers around that like https://straightplugin.readthedocs.io/en/latest/)

The key tradeoffs are that:

- pkgutil based plugin models work for any importable modules in the given namespace, regardless of whether or not they have install-time metadata available. However, there's no way to reliably get the list of available modules without actually looking for them through the Python import system.
- pkg_resources based plugin models require that installation metadata be available (so you'll need to use `pip -e .` or `python setup.py develop` to generate that during development), but offer the benefit that the plugins that will be installed can be determined based on that static metadata without actually installing the component first

So if you want to manage some kind of "plugin catalog", you either need to use the entry point based approach, or come up with your own scheme for publishing the plugin metadata.

If you don't need a programmatically generated catalog though (e.g. when the plugins are just a way of separating out backends for different components and services), then the pkgutil based approach can be simpler to work with.

**Comment by jonparrott** [comment]
@ncoghlan I'm happy to take this as my next writing task or happy to commit to being the reviewer if you want to write it.

**Comment by ncoghlan** [comment]
@jonparrott I think someone else writing with me reviewing works better, as I'm less likely to procrastinate when I'm the reviewer ;)

**Comment by simonvanderveldt** [comment]
@ncoghlan I don't know if you'd want to mention it as a possibility as well, but simply using a prefix as a namespace gives one pretty much the same possibilities as Python's namespace packages.

Flask for example uses a `flask_` prefix for it's extensions , see http://flask.pocoo.org/docs/0.12/extensiondev/#anatomy-of-an-extension
Flask used namespace packages before, but switched because of the incompatibilities discussed in #265, see https://news.ycombinator.com/item?id=4147677)

**Comment by ncoghlan** [comment]
@simonvanderveldt That's a good point, since the Flask model occupies the tier where you don't need any runtime auto-discovery at all - you just want a common naming convention so "the X plugin for Y" is easily discoverable given the names of both X and Y.

That positions the three approaches as:

- naming convention only, automation limited to name generation, filtering and parsing based on that convention
- namespace package traversal for runtime plugin discovery based on Python's import system
- entry points for pre-installation automated discovery based on package index metadata APIs

**Comment by jonparrott** [comment]
@ncoghlan what was the idea behind using `iter_modules`? I can't seem to get it to work in a reasonable way, could you provide an example?

**Comment by jonparrott** [comment]
Hmmm. I think I might have an idea now, maybe something like this?

```python
import pkgutil

import myapp.plugins

plugins = pkgutil.iter_modules(myapp.plugins.__path__)
```

**Comment by ncoghlan** [comment]
@jonparrott Aye, that's the one.
