### ISSUE TITLE
Transfer example namespace package repo, update links

### ISSUE THREAD

**Issue by ncoghlan** [pypa/python-packaging-user-guide#292]
As part of #290, @jonparrott created a sample namespace package repo at https://github.com/jonparrott/namespace-pkg-tests

We have a couple of options for what to do with this repo:

1. Transfer the repo to one of the PyPA org admins/owners and from there into the PyPA org namespace: https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

2. Create a new repo under PyPA, and move the example package repo's contents into there

Either way, the links in the guide will need to be updated, but in the first case they'll also redirect to the new location in the meantime.

@dstufft, @qwcode Do you have any particular preference as to which path we take?

(Note: I'm not currently a PyPA owner/admin, so for either option, either someone else would need to do the transfer/create the repo, or else my privileges would need to be bumped up at the org level)

**Comment by jonparrott** [comment]
FYI- I'm happy to take on the actual "work" here - transferring the contents and updating the guide.

**Comment by dstufft** [comment]
You can transfer them to me and I can transfer into PyPA.

**Comment by jonparrott** [comment]
@dstufft transfer initiated. Thank you. :)

**Comment by jonparrott** [comment]
@dstufft gentle nudge on this.

**Comment by dstufft** [comment]
Sadly the transfer request expired, sorry! If you do it again I can accept it ASAP.

**Comment by jonparrott** [comment]
@dstufft re-initiated. Thanks. :)

**Comment by dstufft** [comment]
Ok it should be transfered now.

**Comment by jonparrott** [comment]
@dstufft thanks! Now it's up to me to update the links in the guide.

**Comment by jonparrott** [comment]
@dstufft can you add me as an admin on that repo? Alternatively, just rename to `sample-namespace-packages`.

**Comment by dstufft** [comment]
I made the Packaging User Guide Editors admin on that repo just now.

**Comment by jonparrott** [comment]
Thanks. @dstufft  :)
