### ISSUE TITLE
setup.py for plugins namespace sub-package

### ISSUE THREAD

**Issue by anthrotype** [pypa/python-packaging-user-guide#295]

**Comment by anthrotype** [comment]
oops, I inadvertently clicked the green button, sorry! Let me write up the full message 😳

**Comment by anthrotype** [comment]
Hello, sorry again for the multiple messages.

I am trying to use the `pkgutil` namespace package approach to provide plugin functionality for my application.

https://github.com/pypa/python-packaging-user-guide/pull/294

The plugin discovery doc says one can use a sub-package (e.g. myapp.plugin) as the namespace package, and also recommends to _not_ make the top-level package (myapp in this case) a namespace package for the purpose of plugins as one bad plugin could break the entire namespace.

I've read the looked at [namespace package user guide](https://github.com/pypa/python-packaging-user-guide/blob/master/source/namespace_packages.rst#pkgutil-style-namespace-packages) and also at the examples at https://github.com/jonparrott/namespace-pkg-tests

In there I can only see examples of top-level namespaces, and no namespace *sub*-packages.

How do I make the setup.py of my plugin install itself under `myapp.plugins` namespace?
Let's assume the `myapp` package is not a namespace, so it will have some non empty __init__.py and other submodules. Say a third-party plugin is called "myapp_plugin_a".
Then how do I lay out its source directory to have it installed under `myapp.plugins`? What should the `myapp` folder contain in the `myapp_plugin_a`'s source? An empty folder, or with an empty `__init__.py`? And will that overwrite myapp's `__init__.py`?

Can you point to other projects where they use pkgutil's namespace packages as *sub*-packages?

**Comment by jonparrott** [comment]
@anthrotype it should "just work" by placing the special ``__init__.py`` into ``myapp/plugins``. It may be the case that the top-level package ``myapp`` also needs to be a namespace package. At Google we use ``google.cloud`` as a namespace subpackage but ``google`` is also a namespace package. I'll confirm and let you know.

**Comment by anthrotype** [comment]
Thank you.

> It may be the case that the top-level package myapp also needs to be a namespace package.

Yes, that's exactly what I'm not sure about.

**Comment by jonparrott** [comment]
@anthrotype confirmed. This works fine, but the plugin packages must omit `__init__.py` from the `myapp` folder. I'll add a note.

**Comment by anthrotype** [comment]
Thanks! But, will setuptools' find_package manage to find the myapp/plugins subfolder if myapp does not have an `__init__.py`?

**Comment by jonparrott** [comment]
@anthrotype nope, you gotta be explicit about it. :)

**Comment by anthrotype** [comment]
oh.. I'd love to see an example of a plugin's setup.py that does that? :)

**Comment by jonparrott** [comment]
@anthrotype 

```python
from setuptools import setup


setup(
    name='example_pkg_a',
    ...
    packages=['example_pkg.plugins.a']
)
```

**Comment by anthrotype** [comment]
Thank you for your help and for working on improving the packaging documentation!

**Comment by jonparrott** [comment]
> Thank you for your help and for working on improving the packaging documentation!

My pleasure!
