### ISSUE TITLE
Expand on using TestPyPI in the distributing guide

### ISSUE THREAD

**Issue by theacodes** [pypa/python-packaging-user-guide#298]
Original context: https://github.com/pypa/python-packaging-user-guide/pull/271#issuecomment-293357309

We already mention that TestPyPI is an option, however, we link off to separate documentation on how to use it. We should self-host this documentation and better surface it in our guide.

**Comment by dstufft** [comment]
FWIW Longish term I want to get rid of TestPyPI, by folding it's primary use case as a baked in feature to Warehouse. Essentially by using https://github.com/pypa/warehouse/issues/726 people can just upload a release without publishing it, then if they don't want to keep it they can just delete it.

**Comment by jonparrott** [comment]
@dstufft what's the timeline on that (if any)?  I just want to know how to prioritize this.

**Comment by dstufft** [comment]
It's lower priority work then getting legacy shut down and migrated, beyond that, whenever someone (or me) feels like working on it.

**Comment by jonparrott** [comment]
Gotcha. :)

**Comment by jonparrott** [comment]
I think this is sufficiently covered by #366 for now, and long-term a new tutorial for publishing packages can mention this.

**Comment by brainwane** [comment]
Now that we have https://packaging.python.org/guides/using-testpypi/ can we close this issue?

**Comment by jonparrott** [comment]
Probably, and I can expand on this more when I get a chance to re-write the
distributing guide.
