### ISSUE TITLE
Possible reference article on "The Packaging Gradient"

### ISSUE THREAD

**Issue by ncoghlan** [pypa/python-packaging-user-guide#310]
@mahmoud just published a good article looking at the many possible layers at which developers can consider the question of application packaging and deployment: http://sedimental.org/the_packaging_gradient.html

I don't think we want to pull that directly into PyPUG, but it seems like it could be useful to reference somewhere as background material for some of the "Additional Topics" sections.

**Comment by jonparrott** [comment]
I'm definitely for this, as it's a fantastic resource for *application* packaging options as opposed to *library* packaging.

**Comment by mahmoud** [comment]
I'm glad you liked it! It's definitely a good introductory that feels good to get out there, and I couldn't have asked for a warmer reception. Even [HN](https://news.ycombinator.com/item?id=14309168) didn't totally hate it! If there's anything I can do to help adapt the content please let me know. I may need some background on the guide (and some time to recover from PyCon), but it sounds like a fun summer activity :)

**Comment by pzwang** [comment]
Just stopping by to add an emphatic +1 on this.  In discussions on Python packaging, we can sometimes get lost on the "how" and the "what", and lose sight of the "why".  Mahmoud's presentation nicely distills down the user job stories about *why* people want to package something, and therefore what is even within the scope of definition of "binary artifact".

(IMO I think 90% of the misunderstandings about conda stem from this simple issue: different people mean vastly different things when they use the word "platform" or "runtime".)

**Comment by ncoghlan** [comment]
Closed via #519 :)
