### ISSUE TITLE
Broken links from setuptools

### ISSUE THREAD

**Issue by azatoth** [pypa/python-packaging-user-guide#321]
https://pypi.python.org/pypi/setuptools is referencing https://packaging.python.org/installing/ which doesn't seems to exists anymore; assuming it's due to recent reorganization.

Clearly it's setuptools' fault for not planning ahead, but I post a ticket here anyway.

**Comment by jonparrott** [comment]
No, this is on us. I setup the redirects but it seems that one isn't working. readthedocs' redirect feature is frustrating. I'll investigate.

**Comment by dstufft** [comment]
Our Fastly config might be breaking the RTD redirects too.

**Comment by jonparrott** [comment]
Ugh I seems I need to do two redirects for every page, one for `/installing` and another for `/installing/` (with trailing slash).

**Comment by jonparrott** [comment]
I'm starting to think @ncoghlan's recommendation to use html redirects is the lesser of two evils.

**Comment by dstufft** [comment]
@jonparrott I can setup Fastly to just blindly redirect ``/<anything>`` to ``/<anything>/`` if we can verify we don't have any paths that don't need to do that.

**Comment by jonparrott** [comment]
@dstufft that seems to be the case. I'm unsure why we went with htmldir instead of just plain html, as it causes weird problems like this. :(

**Comment by jonparrott** [comment]
@dstufft actually that won't fix the redirects we've setup in readthedocs. I'd still need to recreate the all with trailing slashes, so don't worry about it.

**Comment by dstufft** [comment]
@jonparrott Are you familiar with VCL at all?

**Comment by jonparrott** [comment]
@dstufft not really. what are you thinking?

**Comment by dstufft** [comment]
@jonparrott I can give you access to change Fastly settings for PyPUG and you can do redirects and stuff right in VCL which is probably easier than doing it using the RTD control panel since VCL can be done programatically.

Like this is our current VCL:

```vcl
sub vcl_recv {
#FASTLY recv

    if (req.url ~ "\.html$") {
        error 910 "Redirect to HTMLDir";
    }

    if (req.url ~ "^/en/latest/") {
        error 911 "Redirect to Single Version";
    }


    # Do not bother to attempt to run the caching mechanisms for methods that
    # are not generally safe to cache.
    if (req.request != "HEAD" &&
        req.request != "GET" &&
        req.request != "FASTLYPURGE") {
      return(pass);
    }

    # Finally, return the default lookup action.
    return(lookup);
}


sub vcl_error {
#FASTLY error

    if (obj.status == 910) {
        set obj.status = 301;
        set obj.response = "Moved Permanently";
        set obj.http.Location = regsub(req.url, "(/index)?\.html$", "/");
        set obj.http.Content-Type = "text/plain; charset=UTF-8";
        synthetic {"Moved Permanently"};
        return (deliver);
    }
    else if (obj.status == 911) {
        set obj.status = 301;
        set obj.response = "Moved Permanently";
        set obj.http.Location = regsub(req.url, "^/en/latest/", "/");
        set obj.http.Content-Type = "text/plain; charset=UTF-8";
        synthetic {"Moved Permanently"};
        return (deliver);
    }

}
```

Which just does a redirect from ``.html`` to ``/`` and ``/en/latest/`` to ``/``. Figured that might be easier, but VCL is a bit weird so it can be annoying to figure out how to work it.

**Comment by jonparrott** [comment]
@dstufft interesting. I have the entire list of redirects needed defined in [a yaml file](https://github.com/pypa/python-packaging-user-guide/blob/master/scripts/linkmonitor/redirects.yaml). It would likely be possible for me to generate a VCL from that. I'm traveling a bit today but I'll look into that.

In the meantime I've added the extra redirects to readthedocs.

**Comment by jonparrott** [comment]
Closing and moving the VCL recommendation over to #322.
