### ISSUE TITLE
Add flit to the Key Projects list

### ISSUE THREAD

**Issue by ncoghlan** [pypa/python-packaging-user-guide#336]
`flit` 0.11 added the ability to upload sdists, addressing the one concern I had that kept me from personally recommending it as the default choice for packaging pure Python projects. (@takluyver pointed out on distutils-sig that 0.11 is also the version where `flit` switched to uploading to `pypi.org` by default)

`flit` should also have an entry in the Key Projects list.

@takluyver Would you prefer to add flit to the list as a non-PyPA project, or would you be interested in transferring the repo to be under the PyPA org? Being nominally part of PyPA doesn't actually make much difference in terms of the day-to-day operations of the project, it just means you're volunteering to be part of the PyPA collective that governs the default Python packaging experience (and you're effectively doing that already through your work on flit and the build system abstraction API).

**Comment by takluyver** [comment]
Thanks @ncoghlan :-)

I'll have a think about moving flit under the PyPA org. If it picks up a lot of users with the sdist capabilities and PEP 517, I might be glad to put it in an org where other people can more easily get involved with maintenance if they're interested.

I'm working on a module to provide an interface to PEP 517 hooks for frontends; once the PEP is finalised, I'd definitely like to move that under the PyPA org if you're interested.

**Comment by ncoghlan** [comment]
@takluyver I should be explicit that it's also entirely reasonable to add `flit` as a Non-PyPA project for now, and then reconsider whether or not to transfer the repo later. It's a standing offer, rather than a one-time deal :)

**Comment by takluyver** [comment]
Thanks!

I also just remembered a reason you might not want to recommend flit just yet. Once PEP 517 is finalised, I plan to use `pyproject.toml` to store flit metadata (under a tool.flit section). It will continue to interpret `flit.ini` files for a while, but not forever, so people who adopt it now will need to transition at some point. This is why I'm still using 0.x version numbers - I plan to make it 1.0 when it's using `pyproject.toml` by default.

**Comment by ncoghlan** [comment]
OK, that makes sense - we won't add flit to the recommendations until after it has reached 1.0 status. Issue title revised accordingly.

**Comment by dstufft** [comment]
> Being nominally part of PyPA doesn't actually make much difference in terms of the day-to-day operations of the project, it just means you're volunteering to be part of the PyPA collective that governs the default Python packaging experience (and you're effectively doing that already through your work on flit and the build system abstraction API).

Whether flit becomes part of the PyPA officially or not is entirely up to Thomas and I don't mind it either way. I just wanted to point out that pretty much the only requirements we put on projects is that they accepted the PyPA CoC. Beyond that it's entirely up to the individual projects how they manage their projects, who they make contributors, etc.

It's largely just a branding thing tbh, and whether you want to keep it under your brand or the PyPA brand is really the main question. We have major packaging related projects both in and out of the PyPA so either is totally fine.
