### ISSUE TITLE
New TestPyPI URL

### ISSUE THREAD

**Issue by jtemporal** [pypa/python-packaging-user-guide#353]
Hi all!

I was looking for the [new TestPyPI repository URL earlier today](https://twitter.com/jesstemporal/status/889890126977007616) and couldn’t find anywhere.

@ncoghlan [said I could open up a issue](https://twitter.com/ncoghlan_dev/status/890000634421813248) so that this info is added to the migration page 😉

**Comment by ncoghlan** [comment]
And checking https://mail.python.org/pipermail/distutils-sig/2017-June/030766.html, the relevant URL for the test service is https://test.pypi.org/legacy/

**Comment by ncoghlan** [comment]
As a side note, in looking for https://packaging.python.org/guides/migrating-to-pypi-org/, it occurred to me that it probably make sense to add a link directly to that from the bottom of https://packaging.python.org/ and add a short "Migration Status" section to the top of the migration guide.

**Comment by jonparrott** [comment]
The URL is in the migration guide, but it's a little hidden, I'll make it a bit more visible and add a link on the landing page. :)

**Comment by jtemporal** [comment]
Yay! Awesome @jonparrott :)

Thanks!
