### ISSUE TITLE
Document TestPyPI and point wiki.python.org page to these docs

### ISSUE THREAD

**Issue by rsyring** [pypa/python-packaging-user-guide#362]
[Original concern](https://gist.github.com/boppreh/ac7522b3a4ac46b4f6010eecddc57f21) and Donald's reply:

> > Maybe the tutorial is outdated, and TestPyPI supports auto-registration now?
> 
> I don’t think anyone has kept the tutorial on wiki.python.org up to date. To be frank, I don’t even know how to update wiki.python.org. Generally we’ve been trying to consolidate packaging documentation onto packaging.python.org — although I don’t think we have one for TestPyPI yet.

There is reference to TestPyPI [here](https://packaging.python.org/guides/migrating-to-pypi-org/), but maybe it could be expanded.

I have added a deprecation notice to https://wiki.python.org/moin/TestPyPI and mentioned this issue.

**Comment by jonparrott** [comment]
@rsyring with #366 merged, could you update the wiki to just link to https://packaging.python.org/guides/using-testpypi/ ?

**Comment by rsyring** [comment]
@jonparrott done.  Thanks for updating the packaging docs.
