### ISSUE TITLE
Glossary doesn't describe pypi.org

### ISSUE THREAD

**Issue by mpeckWhisker** [pypa/python-packaging-user-guide#363]
The glossary doesn't mention pypi.org (described in a note at the top of https://packaging.python.org/).  Based on that note and the page it links to, it seems like now that pypi.python.org is in read-only mode (post July 27, 2017), it should be described in the glossary.

https://packaging.python.org/glossary/#term-python-package-index-pypi

**Comment by jonparrott** [comment]
Thanks for reporting, @mpeckWhisker, I'll try to address this tomorrow. :)
