### ISSUE TITLE
python pip issue 

### ISSUE THREAD

**Issue by micsanMercy16** [pypa/python-packaging-user-guide#391]
Hi 
I run on my Mac OS X 10.11.6
python -m ensure.pipenv python build.py 
and it does not build the output received is the following. Please advise. Thank you

pkg_resources.RequirementParseError: Expected ',' or end-of-list in ordereddict==1.1; python_version < '3.1' at ; python_version < '3.1'
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 2/21 — 00:00:00
Spawning environment shell (/bin/bash). Use 'exit' to leave.
bash-3.2$ source /Users/micheles/.local/share/virtualenvs/TnGuidanceTextGenerator-PIF-ywqu/bin/activate
(TnGuidanceTextGenerator-PIF-ywqu) bash-3.2$ exit
exit

I tried to remove pip and install it again and same issue. Your answer would be great appreciated. Thank you

**Comment by pradyunsg** [comment]
I think that [python-list](https://mail.python.org/mailman/listinfo/python-list) or [python-tutor](https://mail.python.org/mailman/listinfo/tutor) or #python on Freenode (IRC) would be better channels to get support for the issue you're facing.

This tracker is not the correct place. :)

**Comment by jonparrott** [comment]
I'm going to close this for now, as this doesn't seem like a specific issue with the packaging docs.
