### ISSUE TITLE
`setuptools.setup` parameter `py_modules` is undocumented

### ISSUE THREAD

**Issue by luther9** [pypa/python-packaging-user-guide#397]
I wrote my own distribution package with only one module, but the module file was not being installed along with the dist info file. I found by looking up the code for the `six` module that `setup` has a `py_modules` parameter which apparently must be used to make the installation work. This ~module~ parameter is not mentioned anywhere in https://packaging.python.org/tutorials/distributing-packages/.

**Comment by ncoghlan** [comment]
This is part of the "MANIFEST.in complexity problem", where https://packaging.python.org/tutorials/distributing-packages/#manifest-in is the main docs for how to add files to a setuptools package, and then https://docs.python.org/3.4/distutils/sourcedist.html#specifying-the-files-to-distribute explains which files you'll get included by default if you don't provide one. (The latter is the destination of the "specifying files to include" link in the MANIFEST.in description)

While I'm surprised the https://packaging.python.org/tutorials/distributing-packages/#packages line wasn't sufficient, re-reading https://setuptools.readthedocs.io/en/latest/setuptools.html#using-find-packages shows that indeed, it isn't expected to find single-file modules.

So `py_modules` should probably have its own distinct entry, explaining that it's needed when distributing top level single file modules, without pushing them down inside a package directory.

**Comment by ncoghlan** [comment]
Thanks for the PR @pradyunsg, and thanks for the initial report @luther9!

If we hear anything about folks becoming confused as to whether they need `py_modules` or not, then we may need to clarify what "single file modules" actually means (or equivalently, when the `packages=find_packages(...)`  option on its own isn't sufficient), but just having the section is already a good improvement.

**Comment by pradyunsg** [comment]
Thanks for the merge @ncoghlan!

That sounds like a good way forward.

**Comment by cefn** [comment]
Alternatively, can't packages=['something'] behaviour be extended to handle `something.py` as well as and `something/__init__.py` to prevent people hunting down undocumented arguments for a mainstream way of defining a python module.

That makes more sense to me as an outsider. Any reason this isn't the right way forward? Or is that decision managed by a different project?

**Comment by stigok** [comment]
I'm back here in 2020 struggeling to find information about it. I had to look at the actual commit merged here to figure out what it was.

**Comment by anishpatel** [comment]
It's located here: https://packaging.python.org/guides/distributing-packages-using-setuptools/#py-modules

**Comment by bsolomon1124** [comment]
...though still very much undocumented in [setuptools own documentation](https://setuptools.readthedocs.io/en/latest/setuptools.html).
