### ISSUE TITLE
Mention python3-venv for Debian/Ubuntu setups

### ISSUE THREAD

**Issue by ncoghlan** [pypa/python-packaging-user-guide#399]
Debian & Ubuntu are missing the `ensurepip` module by default for Python 3.5+: you need to install `python3-venv` in order to get it.

https://packaging.python.org/guides/installing-using-linux-tools/ should be updated to mention that.

**Comment by jonparrott** [comment]
@ncoghlan not sure what you mean here, none of the other linux sections suggest installing virtualenv, should I update all of them to install pip, setuptools, wheel, and virtualenv?

**Comment by ncoghlan** [comment]
The problem is that Debian & Ubuntu *remove* ensurepip from their Python 3 installation, so by default "python3 -m venv" doesn't install pip (thus breaking the entire point of PEP 453 and the backport to 2.7).

Other redistributors (including other Linux distros) don't do that - they make venv work properly by default, as the standard library reference indicates they should.

**Comment by jonparrott** [comment]
While confirming this I noticed some unfortuante behavior: `python3 -m venv` *runs* without `python3-venv` but errors, I'm sure users love that:

```
root@ffea451b5ef4:/# python3 -m venv /env
Error: Command '['/env/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1
```
