### ISSUE TITLE
Consolidate pypi.org migration notes

### ISSUE THREAD

**Issue by ncoghlan** [pypa/python-packaging-user-guide#401]
We currently have two sets of pypi.org migration notes:

* https://packaging.python.org/guides/tool-recommendations/#publishing-platform-migration
* https://packaging.python.org/guides/migrating-to-pypi-org/

Aside from duplicating information, the first set also kind of overwhelms that tool recommendation lists that are intended to be the main purpose of that particular guide.

It would be preferable to consolidate all the actual migration notes into the migration guide, and update the section on the tool recommendations page to just link to the migration guide.

**Comment by ncoghlan** [comment]
I'm going to handle this now, as we need to add info about user registration being turned off in legacy PyPI as a result of https://status.python.org/incidents/mgjw1g5yjy5j

**Comment by ncoghlan** [comment]
#401 handles the consolidation, and also adds the note about user registration migrating.

**Comment by brainwane** [comment]
I missed the chance to review #436 before it was merged. Thanks for it, @ncoghlan.

As of earlier this week [we do have package and release management features in Warehouse](https://github.com/pypa/warehouse/milestone/8?closed=1) so I'll update the ["Managing published packages and releases"](https://github.com/pypa/python-packaging-user-guide/blob/master/source/guides/migrating-to-pypi-org.rst#managing-published-packages-and-releases) section with a new PR shortly.
