### ISSUE TITLE
Metadata spec does not mention environment markers

### ISSUE THREAD

**Issue by takluyver** [pypa/python-packaging-user-guide#409]
See [PEP 345](https://www.python.org/dev/peps/pep-0345/#environment-markers), which defines environment markers applying to several fields - most importantly, `Requires-Dist`.

The [core metadata specification](https://packaging.python.org/specifications/core-metadata/#requires-python) page does not say anything about these at present.

**Comment by di** [comment]
I think that's what the [Dependency Specifiers](https://packaging.python.org/specifications/dependency-specifiers/) page is supposed to be. Maybe this should be renamed to "Environment Markers"?

**Comment by takluyver** [comment]
Environment markers are part of that, but not all of it.

I think the core metadata page at least needs to make it clear which fields have environment markers, and where the canonical description of them is.

**Comment by ncoghlan** [comment]
+1 (and enabling that kind of clarification without requiring a PEP update was a key part of the motivation for moving the specs into PyPUG)
