### ISSUE TITLE
Metadata spec: what's a valid name?

### ISSUE THREAD

**Issue by takluyver** [pypa/python-packaging-user-guide#410]
The requires-dist section says:

> The format of a requirement string is identical to that of a distutils project name (e.g., as found in the Name: field...

But the Name field provides no guidance on what is valid.

It looks like the correct answer is [in PEP 508](https://www.python.org/dev/peps/pep-0508/#names): names have to match this (case-insensitive) regex: `^([A-Z0-9]|[A-Z0-9][A-Z0-9._-]*[A-Z0-9])$` . This should be in the metadata spec document, so people don't have to go hunting through PEPs for it.

**Comment by takluyver** [comment]
I may get to these issues myself - I'm just working on some validation code to check that flit makes valid metadata, so I want to write down what the document lacks while I remember it.

**Comment by di** [comment]
The Metadata 1.3 spec should resolve this once accepted. See https://www.python.org/dev/peps/pep-0566/

I have a branch which brings this guide up to date with that PEP -- I'll make a WIP PR for it now so as not to duplicate work.

**Comment by takluyver** [comment]
Thanks @di :-)

**Comment by ncoghlan** [comment]
Since "Update the core metadata page to match PEP 566" is a known task, I don't think we're gaining anything by keeping this open.
