### ISSUE TITLE
Metadata spec: version spec without parentheses?

### ISSUE THREAD

**Issue by takluyver** [pypa/python-packaging-user-guide#411]
The requires-dist section again:

>  optionally followed by a version declaration within parentheses.

[PEP 508](https://www.python.org/dev/peps/pep-0508/#versions) appears to drop the need for the parentheses:

> The optional brackets around a version are present for compatibility with PEP-345 [2] but should not be generated, only accepted.

Does this supersede what's in the spec?

**Comment by di** [comment]
@takluyver Would you mind raising this for discussion within [this distutils-sig thread](https://mail.python.org/pipermail/distutils-sig/2017-December/031788.html)? I think this clarification could easily be included in PEP 566.

**Comment by takluyver** [comment]
Sure!

**Comment by jonparrott** [comment]
@di do you mind if I assign this over to you since you're working on a PR to update Metadata stuff?

**Comment by di** [comment]
@jonparrott Sure, I will fix this in #412.

**Comment by jonparrott** [comment]
Thanks!

**Comment by ncoghlan** [comment]
Since "Update the core metadata page to match PEP 566" is a known task, I don't think we're gaining anything by keeping this open.
