### ISSUE TITLE
Error while building the docs

### ISSUE THREAD

**Issue by Mariatta** [pypa/python-packaging-user-guide#420]
When I ran `make html` I saw this error:

loading intersphinx inventory from https://pypa.io/en/latest/objects.inv...
WARNING: intersphinx inventory 'https://pypa.io/en/latest/objects.inv' not fetchable due to <class 'requests.exceptions.SSLError'>: HTTPSConnectionPool(host='pypa.io', port=443): Max retries exceeded with url: /en/latest/objects.inv (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))
loading intersphinx inventory from https://pip.pypa.io/en/latest/objects.inv...

**Comment by jonparrott** [comment]
/cc @ncoghlan @dstufft 

This is because pypa.io's certificate is borked. I posted about this in pypa-dev a while back but there wasn't a response. Not sure what to do. :/

**Comment by jonparrott** [comment]
I'm going to close this issue as there's nothing we can do here. Whoever has access to pypi.io's hosting/dns will have to fix this.

**Comment by Mariatta** [comment]
Thanks @jonparrott Yeah I figured this is out of the scope for this project.
So who has access to pypi.io? PSF infra?

**Comment by jonparrott** [comment]
Maybe? Summoning @ewdurbin.

**Comment by ewdurbin** [comment]
@Mariatta @jonparrott I don't have access for pypa.io, I think we need @dstufft 

Note: @dstufft I'd be happy to participate as an infra admin for pypa infra :)

**Comment by jonparrott** [comment]
I'm also more than happy to help carry the burden of pypa infra, especially around the docs-related stuff.
