### ISSUE TITLE
Add description of how to view your project to the Using TestPyPI guide and Uploading to PyPI tutorial

### ISSUE THREAD

**Issue by mbacchi** [pypa/python-packaging-user-guide#422]
On the page https://packaging.python.org/guides/using-testpypi/#using-test-pypi the legacy site is still referenced. This should be fixed to use the new warehouse url, which I assume is simply https://test.pypi.org/

**Comment by jonparrott** [comment]
Thanks for reporting @mbacchi! This is super easy bug to fix so I'll see if anyone wants to fix it real quick, otherwise I'll grab it later this week.

**Comment by mbacchi** [comment]
Actually, the legacy URL may still be required. I tried using the url without legacy and got the following errors:

```
[mbacchi@hostname python-git-secrets]$ twine upload --repository testpypi dist/*
Uploading distributions to https://test.pypi.org/
Uploading python_git_secrets-0.0.1-py3-none-any.whl
HTTPError: 405 Client Error: Method Not Allowed for url: https://test.pypi.org/                                         
[mbacchi@hostname python-git-secrets]$ vi ~/.pypirc 
[mbacchi@hostname python-git-secrets]$ twine upload --repository testpypi dist/*
Uploading distributions to https://test.pypi.org/pypi
Uploading python_git_secrets-0.0.1-py3-none-any.whl
HTTPError: 410 Client Error: This API has moved to https://test.pypi.org/legacy/. See TODO for more information. for url: https://test.pypi.org/pypi
[mbacchi@hostname python-git-secrets]$ vi ~/.pypirc 
[mbacchi@hostname python-git-secrets]$ twine upload --repository testpypi dist/*
Uploading distributions to https://test.pypi.org/legacy/
Uploading python_git_secrets-0.0.1-py3-none-any.whl
Uploading python-git-secrets-0.0.1.tar.gz
```

Is the legacy URL required for uploading via twine, but not used in the warehouse URL(i.e.  https://test.pypi.org/ )?

Anyway clarification about the multiple urls is probably good.
Thanks!

**Comment by di** [comment]
@mbacchi Unfortunately it's a bit confusing, `https://test.pypi.org/legacy` is the legacy _API_, not pypi-legacy (which would have been `https://testpypi.python.org/pypi`).

So the URL is correct, for now, although there has been a request to change it to something less confusing: https://github.com/pypa/warehouse/issues/2285.

**Comment by mbacchi** [comment]
Thanks @di. I figured out that if I upload to legacy using twine, the project is visible at https://test.pypi.org/project/PROJECT but it took a little doing to figure out how to verify it was uploaded properly on the frontend. Maybe if there was a section in the Using TestPyPI guide describing how to view the project after upload, we could avoid some confusion.

Let me know what you think. I'd be fine changing this issue's title(or opening another) if you agree and can attempt that doc update if so.

**Comment by di** [comment]
@mbacchi I would agree with that. Seems like it would be worth putting something similar at [Uploading your Project to PyPI](https://packaging.python.org/tutorials/distributing-packages/#uploading-your-project-to-pypi) as well.

**Comment by brainwane** [comment]
@mbacchi #426 added the relevant info to the Using TestPyPI guide - could you add it to the [Uploading your Project to PyPI](https://packaging.python.org/tutorials/distributing-packages/#uploading-your-project-to-pypi) documentation as well? That would be great.
