### ISSUE TITLE
Add pipenv caveat about mixing Python versions

### ISSUE THREAD

**Issue by ncoghlan** [pypa/python-packaging-user-guide#427]
Due to https://github.com/pypa/pipenv/issues/857, pipenv can currently get environment marker evaluation wrong when generating the lock file if the target venv uses a version of Python other than the one running pipenv.

This is most frequently a problem when setting up a Py2 venv from Py3 (due to the prevalence of Py2 only conditional dependencies), but issues can also arise when creating venvs for older Python 3 versions.

**Comment by jonparrott** [comment]
should we just wait for the upstream issue to be addressed or do we anticipate this guide needing this caveat long-term?

**Comment by ncoghlan** [comment]
I think it's worth adding the caveat in the near term, as the `pipenv` folks have been trying different ways of fixing this over the past few releases, and it isn't clear yet when a more robust approach to mixing and matching Python versions will ship.

As things currently stand, we're seeing folks trying to use a recent Python 3 to manage Python 2.7 projects (rather than developing & deploying on the same Python version), and wondering why their Python-2-only dependencies aren't showing up properly (and getting an overly negative impression of pipenv as a result).

Even after it's fixed, we may want to keep the caveat in some form, just noting the minimum version needed for reliable cross-version operation.

**Comment by jonparrott** [comment]
Sounds good. I'll try to get this up this week, but if someone wants to send a PR to beat me to it I'll merge quickly. :)
