### ISSUE TITLE
Provide pointer to Google Big Query download statistics

### ISSUE THREAD

**Issue by ncoghlan** [pypa/python-packaging-user-guide#428]
(I thought there was already an open issue for this, but I can't find it, so filing this one)

We don't really have the Google Big Query download stats documented anywhere. https://mail.python.org/pipermail/distutils-sig/2016-May/028986.html is the original announcement, and https://langui.sh/2016/12/09/data-driven-decisions/ is a good blog post about them, but neither is particularly discoverable for package maintainers.

**Comment by tswast** [comment]
In addition to pointing them at the dataset & blog post, it could be good to link to pypinfo, which bundles up some handy queries for package maintainers. https://github.com/ofek/pypinfo

**Comment by jonparrott** [comment]
chatted with @tswast and he's going to take this on. :)

**Comment by tswast** [comment]
I suppose this would be a [Guide](https://packaging.python.org/guides/). A title for the guide could be something like "Analyzing PyPI package downloads".

**Comment by ncoghlan** [comment]
+1 to structuring this as guide and using that title.
