### ISSUE TITLE
document `--user` option for core tool installs

### ISSUE THREAD

**Issue by qwcode** [pypa/python-packaging-user-guide#43]
consider documenting (assuming we test it more) that you can `get-pip.py --user`, and mention `--user` as a possibility for the install of `virtualenv` (and `wheel`, and `twine` too, if not in a virtualenv)

see https://github.com/pypa/pip/issues/1668

**Comment by adamn** [comment]
I believe this is complete (https://packaging.python.org/installing/#installing-to-the-user-site)

**Comment by jonparrott** [comment]
Thanks, @adamn!
