### ISSUE TITLE
Update news with updates Dec 2017-present

### ISSUE THREAD

**Issue by brainwane** [pypa/python-packaging-user-guide#474]
https://packaging.python.org/news/ currently stops in November 2017; let's update it.

**Comment by pradyunsg** [comment]
@brainwane Would this be something for the Sprint?

**Comment by jonparrott** [comment]
This is something for me to do during the sprint. (And something for me to
add a build check for.)

**Comment by theacodes** [comment]
This is a great issue for a first-time contributor to take on. Building a check (or using something more complex) would be a task for me.

**Comment by pradyunsg** [comment]
If you go along the route of combining smaller NEWS fragments, I suggest looking at towncrier. It's working well for pip.

**Comment by dwalkerbeta** [comment]
I could take this task, if no one else has taken it. Where would be the best place to curate the news from?

**Comment by theacodes** [comment]
@dwalkerbeta the commit log is probably the best ledger we have.

**Comment by dwalkerbeta** [comment]
Ok, that's where I've been pulling from. I'll probably have a PR out this weekend for the in-place solution and I'm currently looking into towncrier as a longer-term solution.

**Comment by theacodes** [comment]
Thank you so much!

**Comment by dwalkerbeta** [comment]
I'm testing out the towncrier solution; I have a few questions. It looks like towncrier names its newsfragment files with _issueid.doc_ or _issueid.feature_. Would we want to replace those with the PR numbers? Some of the PRs don't have an issue assigned to them.

Also, is there any sort of versioning that has been adopted? Right now the --draft option from towncrier looks like this with the earliest fragment from news.rst:

```Loading template...
Finding news fragments...
Rendering news fragments...
Draft only -- nothing has been written.
What is seen below is what would be written.

Python Packaging User Guide 1.0 (2017-02-01)
============================================


Improved Documentation
----------------------

- Added :pep:`518`. (:pr:`281`) (#281)
```

And I can increment the version per month, or just push all past changes out under 1.0 and you guys increment from there.

Thoughts?

**Comment by dwalkerbeta** [comment]
How would the calver be formatted? Also I figure I'll remove the duplicated PR in the ().

**Comment by theacodes** [comment]
2018.11.05

(year.month.day)

**Comment by dwalkerbeta** [comment]
Which format would you want the news page to follow?
Old:
```
News
====

May 2017
--------

- Added documentation for the ``Description-Content-Type`` field. (:pr:`258`)
- Added contributor and style guide. (:pr:`307`)
- Documented ``pip`` and ``easy_install``'s differences for per-project indexes. (:pr:`233`)

April 2017
----------

- Added travis configuration for testing pull requests. (:pr:`300`)
- Mentioned the requirement of the ``wheel`` package for creating wheels (:pr:`299`)
- Removed the ``twine register`` reference in the *Distributing Packages* tutorial. (:pr:`271`)
- Added a topic on plugin discovery. (:pr:`294`, :pr:`296`)
- Added a topic on namespace packages. (:pr:`290`)
- Added documentation explaining prominently how to install ``pip`` in ``/usr/local``. (:pr:`230`)
- Updated development mode documentation to mention that order of local packages matters. (:pr:`208`)
- Convert readthedocs link for their ``.org`` -> ``.io`` migration for hosted projects (:pr:`239`)
- Swaped order of :file:`setup.py` arguments for the upload command, as order
  is significant. (:pr:`260`)
- Explained how to install from unsupported sources using a helper application. (:pr:`289`)

```

New:
```
News
====

May 2017
--------

Page Updates
~~~~~~~~~~~~

- Documented ``pip`` and ``easy_install``'s differences for per-project indexes. (:pr:`233`)
- Added documentation for the ``Description-Content-Type`` field. (:pr:`258`)


New Pages
~~~~~~~~~

- Added contributor and style guide. (:pr:`307`)


April 2017
----------

Features
~~~~~~~~

- Added travis configuration for testing pull requests. (:pr:`300`)


Page Updates
~~~~~~~~~~~~

- Updated development mode documentation to mention that order of local packages matters. (:pr:`208`)
- Added documentation explaining prominently how to install ``pip`` in ``/usr/local``. (:pr:`230`)
- Convert readthedocs link for their ``.org`` -> ``.io`` migration for hosted projects. (:pr:`239`)
- Swapped order of :file:`setup.py` arguments for the upload command, as order is significant. (:pr:`260`)
- Removed the ``twine register`` reference in the *Distributing Packages* tutorial. (:pr:`271`)
- Explained how to install from unsupported sources using a helper application. (:pr:`289`)
- Added a topic on plugin discovery. (:pr:`296`)
- Added a topic on namespace packages. (:pr:`290`)
- Mentioned the requirement of the ``wheel`` package for creating wheels. (:pr:`299`)
```

The advantage of the old format is the readability, everything is just in bullet points. With the new format we could take advantage of towncrier's list-by-fragment-type feature (.doc, .new) but it doesn't look as "clean".

Let me know what you think.

**Comment by theacodes** [comment]
I'm fine with either.

**Comment by ncoghlan** [comment]
I like the categorised one, but I'd retitle "Features" as something like "User Guide Development Updates" and list them after the more user facing categories.

**Comment by CMeza99** [comment]
I think this issue is resolved :)

**Comment by ncoghlan** [comment]
Indeed - closing! :)
