### ISSUE TITLE
Document project_urls in Core metadata specifications

### ISSUE THREAD

**Issue by nixjdm** [pypa/python-packaging-user-guide#480]
https://packaging.python.org/specifications/core-metadata/#project-url-multiple-use is missing a section for project_urls. This should be added.

**Comment by nixjdm** [comment]
@di Sorry for the confusion. I linked to where I did because that's close to where a `project_urls` section would live, so that with a small amount of scrolling you could see that the section doesn't exist.

There is a `project_urls` section in the tutorial, but not in the metadata specifications page. There should be a section in the specs as well, particularly for this, because it's spec is not common among the the other metadata fields, and more complicated. A `setup.py` could have `project_urls` as a dict, and ordereddict, etc, on top of the sub-spec of each `project_url`.

**Comment by nixjdm** [comment]
@di Yes, maybe I was / am confused. I was looking at https://github.com/pypa/warehouse/blob/b38745817f1f9a3d929de043f7e99bcd4963154c/warehouse/forklift/legacy.py#L543-L558, and thinking since requires_external is in the specs, project_urls should be too. I didn't notice the case sensitivity though, which should have been a clue.

It seems the name of the core metadata that is documented, is more related to the description attributes in that legacy.py, than the higher-level MetadataForm attributes, is that right? I.e. MetadataForm has a `project_urls` attribute, that has a description attribute equal to `Project-URL`, and we choose the name from that last one. I notice now that MetadataForm has a `project_urls` attribute, but not a separate `project_url` attribute.

So then all of the core metadata (AFAIK) is documented, and I was just confused by naming. I think :)

**Comment by di** [comment]
@nixjdm Yes, the upload API more or less mimics the setuptools kwargs. Since `Project-URL` is multiple use, it becomes `project_urls` instead of `project_url`. The `description` bit is just so that we can generate a link to the spec when necessary.

That's a great point about commas though. I agree that it should probably be documented somewhere (possibly in multiple places).

**Comment by nixjdm** [comment]
Alright, thanks for setting me straight @di. I'll close this. I'll open ticket for updating that the setuptools docs for that repo, and anywhere else with your recommendation, or you can ;)

Thanks!
