### ISSUE TITLE
Feedback from PyCon sprint on package creation tutorial

### ISSUE THREAD

**Issue by brcrista** [pypa/python-packaging-user-guide#494]
(@brainwane asked me to write this, despite not being a well-formed issue)

During the PyCon sprint for Python packaging, I worked through the [tutorial](https://packaging.python.org/tutorials/distributing-packages/#configuring-your-project) and wrote down pain points or places I got stuck.

* The material is good, but it is written more as a reference than as a tutorial.  I had to read through a [long section on optional arguments to `setup()`](https://packaging.python.org/tutorials/distributing-packages/#setup-args) before getting to how to build and upload a package.
* It would be more instructive to create a minimal example package, build an sdist, and upload it to <https://test.pypi.org>.  The reference material can come later, or on a separate page.
* Minor issue: it's not clear to me after doing the tutorial what the difference between an sdist and a universal wheel is, or when I would prefer one over the other.

Otherwise, I think the content is accurate and the right level of detail.

**Comment by theacodes** [comment]
Just a heads up that I've started re-writing the tutorial on the plane ride home. This feedback directly fits with my assessment of the current tutorial.
