### ISSUE TITLE
Packaging and distributing {projects -> libraries} 

### ISSUE THREAD

**Issue by pradyunsg** [pypa/python-packaging-user-guide#503]
https://packaging.python.org/guides/distributing-packages-using-setuptools/

The title of this page is "Packaging and distributing projects". Maybe we should change projects to libraries in this title since that's a better fit.

Context - I've had a beginner friend who was trying to convert a python script to something he could share (as a stand-alone executable) and he thought this guide would help with that, due to the title.

**Comment by pradyunsg** [comment]
Same thing for https://packaging.python.org/tutorials/packaging-projects/

**Comment by ncoghlan** [comment]
These both deliberately say "projects" in order to match `pyproject.toml`. We also want to avoid getting into a definitional debate about library vs framework, and you can also distribute applications this way when your intended audience is other Python developers.
