### ISSUE TITLE
Confusing Python Package Next Steps

### ISSUE THREAD

**Issue by ademidun** [pypa/python-packaging-user-guide#510]
The [instructions for uploading to pypi.org](https://packaging.python.org/tutorials/packaging-projects/#next-steps) instead of uploading to test.pypi.org are worded in a slightly confusing manner.
Currently:
> If you want to upload your package to the real Python Package Index you can do it by registering an account on https://pypi.org and following the same instructions above but **omitting** the --repository-url argument **to** twine and the --index-url argument **to** pip.

Should be

> If you want to upload your package to the real Python Package Index you can do it by registering an account on https://pypi.org and following the same instructions above but **ommitting** the --repository-url argument **in** twine upload and the --index-url argument **in** pip install.

**Comment by ncoghlan** [comment]
Rather than describing how to change the commands, I'm wondering if we might be better off putting the post-modification commands directly in this section. @theacodes, your thoughts?

**Comment by theacodes** [comment]
Yeah definitely.
