### ISSUE TITLE
Suggested order for classifers?

### ISSUE THREAD

**Issue by gtback** [pypa/python-packaging-user-guide#532]
1. Is there a suggested order for the values in the `classifiers` kwarg to `setup()`? I looked in a bunch of places, and didn't find anything definitive:

    - https://packaging.python.org/tutorials/packaging-projects/
    - https://pypi.org/classifiers/
    - https://www.python.org/dev/peps/pep-0301/#distutils-trove-classification
    - https://github.com/pypa/sampleproject
    - https://packaging.python.org/specifications/core-metadata/#classifier-multiple-use

    [PEP 301](https://www.python.org/dev/peps/pep-0301/#distutils-trove-classification) shows them in alphabetic order. [`sampleproject`](https://github.com/pypa/sampleproject/blob/master/setup.py) shows them in an order that makes some logical sense (and has comments) but is not alphabetical. [PyPI.org](https://pypi.org/classifiers/) shows all of the classifiers in alphabetical order. 

    A (non-scientific) survey of a few popular packages:
    - [Django](https://github.com/django/django/blob/master/setup.py) and [dateutil](https://github.com/dateutil/dateutil/blob/master/setup.py) are alphabetical.
    - [Requests](https://github.com/requests/requests/blob/master/setup.py) and [botocore](https://github.com/boto/botocore/blob/develop/setup.py) are mostly alphabetical (but `Natural Language` is above `License`).
    - [Pip](https://github.com/pypa/pip/blob/master/setup.py) is mostly alphabetical (but `Topic` is above `Programming Language`).
    - [cryptography](https://github.com/pyca/cryptography/blob/master/setup.py) is alphabetical at the top level, but `Operating System :: Microsoft :: Windows` is out of place.
    - [Six](https://github.com/benjaminp/six/blob/master/setup.py) is not in any particular order that I can tell.

2. Should the Packaging User Guide suggest an order?

**Comment by theacodes** [comment]
At the moment, I don't see much benefit in calling out that the classifiers are an unordered list (it's additional information that isn't immediately useful to the developer). What's great is that now that this issue exists, a cursory google search will reveal the answer to the question.

I'm closing this for now, but if anyone feels strongly the that the tutorial or the setuptools docs should be more explicit about this, let me know.
