### ISSUE TITLE
Minimum version requirement of setuptools to render markdown on PyPI

### ISSUE THREAD

**Issue by hsiaoyi0504** [pypa/python-packaging-user-guide#535]
It's related to issue pypa/setuptools#1440 and pypa/warehouse#4341.

It seems to me that the minimum version used of setuptool need to be updated, but doesn't have a conclusion yet.

Or we need to add a notice about building on Windows.

**Comment by theacodes** [comment]
We list the minimum versions here: https://packaging.python.org/guides/making-a-pypi-friendly-readme/#including-your-readme-in-your-package-s-metadata

Is this insufficient/incorrect?

**Comment by hsiaoyi0504** [comment]
The libraries used in those issues are
```
wheel==0.31.1
setuptools==39.1.0
twine==1.11.0
```
meets current requirements:
```
setuptools >= 38.6.0
wheel >= 0.31.0
twine >= 1.11.0
```

**Comment by di** [comment]
This is unrelated to the Markdown or the long_description_content_type field, see my comment here: https://github.com/pypa/setuptools/issues/1440#issuecomment-408544575

It's possible that this is a bug in setuptools/pkginfo/twine but otherwise the versions currently listed are sufficient for using this field.

**Comment by hsiaoyi0504** [comment]
@di I know what you mean, but I opened was because that I expected there will be a fix and a new release. Therefore, there will be a need to update the document or add a postscript about that. It’s a reminder that don’t forget to update the document as well.

**Comment by zxc751176723** [comment]
不懂

**Comment by theacodes** [comment]
As far as I can tell, there's no action for this project here. Please let me know if I misunderstood.
