### ISSUE TITLE
Usage of exec in option three of "Single-sourcing the package version"

### ISSUE THREAD

**Issue by Syndace** [pypa/python-packaging-user-guide#536]
Option three described [here](https://packaging.python.org/guides/single-sourcing-package-version/) recommends the usage of exec to load a file containing the version. I'm a little confused as to why exec is used instead of a simple import.

I read about the differences between import and exec in search for an explanation but it didn't make things more clear.

Are
```Python
os.path.append("/path/containing/version.py/")
from version import __version__
```
and
```Python
execfile("/path/containing/version.py/version.py")
```
the same? Is there any reason to prefer `execfile`?

I always try to avoid functions like `eval`, `exec` and the like.

**Comment by dstufft** [comment]
Hit the wrong button sorry.

Generally the reason it's done using ``exec`` is because it's less likely to trigger an import that may require dependencies to already have been installed.

**Comment by Syndace** [comment]
Alright, so in case of a version file that includes just one single line:
```Python
__version__ = "foo"
```
there should be no problem with using the `import` variant.

Thank you very much.
