### ISSUE TITLE
Unauthenicated upload; Successful login

### ISSUE THREAD

**Issue by Skarlett** [pypa/python-packaging-user-guide#588]
Everytime I attempt to upload to the repository - I get this error message. I've tried my email and password combo, my username, and password combo (Which all work on pypi.org). Recently my account was found to be compromised; I recommissioned it today, and all seemed alright until I attempted to upload a project.

Error message:
`HTTPError: 403 Client Error: Invalid or non-existent authentication information. for url: https://test.pypi.org/legacy/`

**Comment by di** [comment]
@Skarlett https://pypi.org and https://test.pypi.org are completely separate. You'll need to create an account on https://test.pypi.org as well.

**Comment by theacodes** [comment]
@Skarlett I think @di has found the solution to your problem. I'm going to go ahead and close this, but please let us know if you have any more questions.
