### ISSUE TITLE
Please include sphinx

### ISSUE THREAD

**Issue by guettli** [pypa/python-packaging-user-guide#63]
Please include some basic instructions where to put sphinx docs.

I don't want a copy of sphinx introduction, but a basic help how to layout
the  directory of the docs.

I know that anybody can use the structure he wants, but a basic best practice guideline would help people which are new to python.

**Comment by ncoghlan** [comment]
There's some more discussion of adding Sphinx-related recommendations in #101, so let's try to focus the (belated) discussion there.
