### ISSUE TITLE
Use HTMLDir

### ISSUE THREAD

**Issue by dstufft** [pypa/python-packaging-user-guide#65]
The default on RTD is to use Sphin'x HTML output, which does something lame like https://packaging.python.org/en/latest/current.html which is not a pretty URL. It would be great if instead this used HTMLDir which would give an URL like https://packaging.python.org/en/latest/current/ which is prettier!

**Comment by qwcode** [comment]
@ncoghlan , let's go ahead and switch to htmldir, ok?  

it would help with nicer spec links, if we go down that road.

RTD makes the transition painless, with this setting  https://read-the-docs.readthedocs.org/en/latest/user-defined-redirects.html#sphinx-redirects

**Comment by qwcode** [comment]
ok, this is done.   I was doing it for pip, which ended up requiring fastly changes, so  I asked @dstufft to go ahead and make the changes for PyPUG as well.
