### ISSUE TITLE
Reconcile RTD URL and canonical packaging.python.org URL

### ISSUE THREAD

**Issue by dstufft** [pypa/python-packaging-user-guide#66]
So right now we're using the excellent RTD platform for hosting this guide. However the old URL is still floating around and a lot of people don't know about the https://packaging.python.org/ URL.

Maybe it would be a good idea to move to hosting this ourselves (or use a different hidden name) and have the old long name use a HTML redirect or even just say that the guide has moved. Maybe we can even get RTD to do a proper redirect?

**Comment by pradyunsg** [comment]
Does this issue mean redirecting from python-packaging-user-guide.readthedocs.io to packaging.python.org?

What about the various pages on wiki.python.org? It seems to me that updating them and linking them to the new packaging.python.org is a useful change...

**Comment by jonparrott** [comment]
> Does this issue mean redirecting from python-packaging-user-guide.readthedocs.io to packaging.python.org?

Possibly, but I don't feel like that's much of an issue any longer.

> What about the various pages on wiki.python.org?

If we're gonna do that, we should track that separately. Very few of us have edit access to the wiki.

**Comment by pradyunsg** [comment]
> Maybe we can even get RTD to do a proper redirect?

This issue would be a nice to have then, I guess.

**Comment by brainwane** [comment]
There are still a bunch of old links out on the web (e.g., in people's blog posts) that point at pages like https://python-packaging-user-guide.readthedocs.io/en/latest/current.html . @ericholscher could you help make a redirect happen?

**Comment by ncoghlan** [comment]
Hmm, I actually thought we had this configured in our RTD settings, but it doesn't seem like that's the case.

I've added python-packaging-user-guide.readthedocs.io back to the domain list, to see if that at least gets those links resolving again.

**Comment by brainwane** [comment]
Nope, link still does not resolve. @jonparrott can you take a look?

**Comment by jonparrott** [comment]
Yeah. Hrm, it's weird to serve the same content from different domains. @ericholscher is there any way to set a "canonical domain" in such a way that `python-packaging-user-guide.readthedocs.io` redirects transparently to `packaging.python.org`? (GitHub appears to do this with github pages and custom domains).

If not - would you be open to such a feature? I can contribute it if you point me in the right direction.

**Comment by ncoghlan** [comment]
After fiddling with the settings again, I'm thinking this may actually be an RTD bug, as it correctly removes the `en/latest` segment from the path for `packaging.python.org`, but fails to do so for `python-packaging-user-guide.readthedocs.io`. As a result, the following three URLs all end up at the right place (redirecting to `guides/tool-recommendations` in the corresponding domain):

* https://packaging.python.org/current -> https://packaging.python.org/guides/tool-recommendations
* https://packaging.python.org/en/latest/current -> https://packaging.python.org/guides/tool-recommendations
* https://python-packaging-user-guide.readthedocs.io/current -> https://python-packaging-user-guide.readthedocs.io/guides/tool-recommendations

However, this one 404s:

* https://python-packaging-user-guide.readthedocs.io/en/latest/current

I don't thinking having the two domains is that much of a problem - it's the fact that last link currently 404s that's a potential concern.

**Comment by jonparrott** [comment]
Alright, how do we go about getting this resolved, then?

**Comment by dstufft** [comment]
Seems so, thanks @ericholscher !
