### ISSUE TITLE
 "Terminology Usage and Pronunciation Guide"

### ISSUE THREAD

**Issue by qwcode** [pypa/python-packaging-user-guide#89]
pasted from https://github.com/pypa/python-packaging-user-guide/issues/87#issuecomment-53976137
(from @ncoghlan )

So my proposal would be that we add a separate "Terminology Usage and Pronunciation Guide", distinct from the existing glossary, as it's primarily useful to folks writing documentation and creating presentations, rather than being necessary for folks reading or watching them.

Writing that would be where I agree the more explicit "distribution package" and "import package" terms can help:
- "distribution package" always refers to "thing you can download and install"
- "distribution" usually refers to "distribution package" but, depending on context, may refer to the overall field or to Linux distributions. In PyPA documentation, it should _only_ be used in the "distribution package" sense.
- "software distribution and packaging" always refers to the overall field, as do "software distribution" and "packaging" on their own. Hence, these are the preferred terms for this concept in PyPA documentation (as "distribution" is reserved to mean "distribution package"). The PyPA, PyPI and PyPUG names use the term "Packaging" in this sense.
- "distro" always refers to a Linux distribution, and hence is the preferred for this concept in PyPA documentation (as "distribution" is reserved to mean "distribution package").
  - "import package" always refers to "thing you can import that may have submodules"
  - "package" usually refers to "import package" but, depending on context, may refer to "distribution package". In PyPA documentation, it should _only_ be used in the "import package" sense.

As far as disambiguation when speaking goes, perhaps we should include a pronunciation guide in the tutorial or glossary, and explicitly give the reason why the pronunciation matters? I always say pie-pee-eye myself, specifically due to pie-pie being a homonym with PyPy. (I'm also a fan of any extra subtle advertising we can give PyPy, since that's a highly valuable project that's genuinely advancing the state of the art in dynamic language interpreters)

So that would be something like:
- PyPI (Python Packaging Index): said aloud by using its full name, or by spelling out the last two letters, as in "Py-P-I". Alternatives are to abbreviate as the "Packaging Index", or to use the colloquial nickname "the Cheese Shop" (which refers to the name of a Monty Python's Flying Circus sketch). Referring to the packaging index aloud as "Py-Py" is strongly discouraged, as "PyPy" is the name of a popular alternative Python interpreter.
- PyPA (Python Packaging Authority): said aloud by using its full name, or by spelling out the last two letters, as in "Py-P-A". Alternatives are to abbreviate as the "Packaging Authority" or to use the mailing list name where the Python packaging related interoperability standards are discussed, `distutils-sig` (which refers to the distutils standard library module, created in 1998 as the initial iteration of a standardised source based packaging and distribution system for Python).
- PyPUG (Python Packaging User Guide): said aloud by using its full name, or by pronouncing the second half like the dog breed, as in "Py-pug". Alternatives are to abbreviate as the "Packaging User Guide", or to use the domain name where the guide is hosted, `packaging.python.org`.

If this sounds acceptable to folks, @cjrh suggested I run a "how you can help improve Python packaging" session at the September Brisbane Python User Group session, and (assuming that happens) this could be a good thing for us to work on contributing.

**Comment by pradyunsg** [comment]
This can be closed?

**Comment by jonparrott** [comment]
I think so. Closing but we can always re-open.
