### ISSUE TITLE
Add a section on building Windows binary wheels using a CI services (appveyor)

### ISSUE THREAD

**Issue by pfmoore** [pypa/python-packaging-user-guide#93]
I want to include a section in the official user guide on how to set up automatic wheel builds for Windows. The idea is to give projects a simple "cookbook" approach to getting wheels, without needing access to Windows environments, etc.

Some possible issues:

1. We don't cover testing in the PUG, so is it OK to describe setting up to CI services?
2. Is it OK to promote appveyor here? To my knowledge, there is no available alternative at the moment, but obviously that may change.

Also, a technical issue - I need to provide a couple of files to be copied into the user's project (```appveror.yml``` and a couple of scripts to install ```pip``` and ```wheel``` and set up the compiler environment). How should I include these? I'd like to have them inline as text, and also linked so that people can download them. Where to host them?

Alternatively, if this is not suitable for the PUG, where would be a good place to publish a document like this? Maybe we should start a series of "Packaging HOWTO" guides? Or a PyPA blog?

**Comment by jayvdb** [comment]
PR merged. Time to close this one?
